Repository hmcts/probate-frontend, pull requests merged in 2018-12, with the labels that each got.

#429 PRO-1441: DoB and DoD validation
  app/core/steps/DateStep.js
  app/resources/en/translation/deceased/dob.json
  app/resources/en/translation/deceased/dod.json
  app/steps/ui/deceased/dob/index.js
  app/steps/ui/deceased/dod/index.js
  test/component/deceased/testDoB.js
  test/component/deceased/testDoD.js
  test/unit/testDeceasedDob.js
  test/unit/testDeceasedDod.js
Labels: ns:probate-frontend-pr-429, screening questions

#480 PRI-119 - Answers to screener questions being persisted in the formdata
  app/steps/ui/applicant/newexecutor/index.js
  app/steps/ui/deceased/newdeathcertificate/index.js
  app/steps/ui/deceased/newdomicile/index.js
  app/steps/ui/executors/newmentalcapacity/index.js
  app/steps/ui/iht/newcompleted/index.js
  app/steps/ui/will/newleft/index.js
  app/steps/ui/will/neworiginal/index.js
  yarn.lock
Labels: ns:probate-frontend-pr-480, screening questions

#486 PRO-1930: Added content to start page and create account page
  app/resources/en/translation/common.json
  app/resources/en/translation/newstartapply.json
  app/resources/en/translation/newstarteligibility.json
  app/steps/ui/newstartapply/template.html
  app/steps/ui/newstarteligibility/template.html
Labels: ns:probate-frontend-pr-486, screening questions

#469 PRI-111 - Tech: Change commit message git hook
  app/components/services.js
  commit-msg.sh
Labels: intestacy, ns:probate-frontend-pr-469

#496 Pro 3750 upload check your answers
  app/featureToggles.js
  app/resources/en/translation/documentupload.json
  app/resources/en/translation/summary.json
  app/steps/ui/summary/includes/documentupload.njk
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  kubernetes/config.aat.yaml
  test/component/summary/testDocumentUploadSection.js
  test/component/summary/testSummary.js
  test/data/documentupload.json
  test/unit/testSummary.js
Labels: document upload, ns:probate-frontend-pr-496

#477 PRO-4273 - Doc Upload: Documents section should still be present on CYA even if no Doc uploaded
  app/resources/en/translation/summary.json
  app/steps/ui/summary/includes/documentupload.njk
  app/steps/ui/summary/template.html
  app/views/widgets/checkanswer.html
  test/component/summary/testDocumentUploadSection.js
  test/component/summary/testSummary.js
Labels: document upload, ns:probate-frontend-pr-477

#493 PRO-3775 and PRO-3489 - Document upload...uploading and removing documents to/from DM
  app/assets/javascripts/document-upload.js
  app/config.js
  app/resources/en/translation/common.json
  app/resources/en/translation/documentupload.json
  app/utils/DocumentUpload.js
  app/views/includes/scripts.html
  kubernetes/config.aat.yaml
  test/unit/testDocumentUpload.js
  test/unit/testDocumentUploadUtil.js
  yarn.lock
Labels: document upload, ns:probate-frontend-pr-493

#500 Pro 4317 add payment logging
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
Labels: bau, ns:probate-frontend-pr-500

#425 PRO-3757 - Upload death certificate - upload timeout
  app/resources/en/translation/documentupload.json
  test/unit/testDocumentUpload.js
  yarn.lock
Labels: document upload, ns:probate-frontend-pr-425

#427 PRO-3777 - Upload death certificate - upload timeout - non JS
  app/resources/en/translation/common.json
  app/resources/en/translation/documentupload.json
  test/unit/testDocumentUpload.js
  test/unit/testDocumentUploadMiddleware.js
Labels: document upload, ns:probate-frontend-pr-427

#445 PRO-3818 - Upload death certificate - link page into main journey
  app/steps/ui/deceased/address/index.js
  test/unit/testDeceasedAddress.js
  yarn.lock
Labels: document upload, ns:probate-frontend-pr-445

#509 PRO-3488: missing doc upload map added to submit
  app/components/submit-data.js
Labels: ns:probate-frontend-pr-509

#511 PRO-4077 - Update documents page with SI changes
  app/resources/en/translation/documents.json
  app/steps/ui/documents/template.html
  test/component/testDocumentsPage.js
Labels: ns:probate-frontend-pr-511

#446 Pro 2795 remove escaped characters in declarartion
  app/resources/en/translation/declaration.json
  infrastructure/preview.tfvars
Labels: bau, ns:probate-frontend-pr-446

#503 PRI-110: Set expiry date on eligibility cookie to 2 days
  app/config.js
  app/core/runners/UIStepRunner.js
  app/core/steps/EligibilityValidationStep.js
  app/core/steps/Step.js
  app/steps/ui/applicant/newexecutor/index.js
  app/steps/ui/deceased/newdeathcertificate/index.js
  app/steps/ui/deceased/newdomicile/index.js
  app/steps/ui/executors/newmentalcapacity/index.js
  app/steps/ui/iht/newcompleted/index.js
  app/steps/ui/will/newleft/index.js
  app/steps/ui/will/neworiginal/index.js
  app/utils/EligibilityCookie.js
  test/component/applicant/testNewExecutor.js
  test/component/deceased/testNewDomicile.js
  test/component/executors/testNewMentalCapacity.js
  test/component/iht/testNewIhtCompleted.js
  test/component/testNewStartApply.js
  test/component/will/testNewWillLeft.js
  test/component/will/testNewWillOriginal.js
  test/unit/testEligibilityCookie.js
  test/unit/testEligibilityValidationStep.js
  test/unit/testNewApplicantExecutor.js
  test/unit/testNewDeathCertificate.js
  test/unit/testNewDeceasedDomicile.js
  test/unit/testNewIhtCompleted.js
  test/unit/testNewMentalCapacity.js
  test/unit/testNewWillLeft.js
  test/unit/testNewWillOriginal.js
  test/unit/testStep.js
Labels: ns:probate-frontend-pr-503, screening questions

#506 Pro 3549 check answers summary pdf
  app/assets/sass/application-common.scss
  app/components/api-utils.js
  app/components/pdf-services.js
  app/config.js
  app/core/runners/UIStepRunner.js
  app/core/steps/Step.js
  app/core/steps/ValidationStep.js
  app/documentDownload.js
  app/resources/en/translation/summary.json
  app/routes.js
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  app/utils/CheckAnswersSummaryJSONObjectBuilder.js
  docker-compose.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  package.json
  test/config.js
  test/end-to-end/pages/summary/summary.js
  test/unit/testCheckAnswersSummaryJSONObjectBuilder.js
  test/unit/testDocumentDownload.js
  test/util/TestWrapper.js
Labels: document download, ns:probate-frontend-pr-506

#515 PRO-4359: Fix bug with Deceased Task status not getting set properly …
  app/featureToggles.js
  app/steps/ui/deceased/address/index.js
  test/component/deceased/testAddress.js
  test/unit/testDeceasedAddress.js
Labels: bau, ns:probate-frontend-pr-515

#521 PRO-4389 - Declaration page changes for will SI
  app/resources/en/translation/declaration.json
  app/steps/ui/declaration/index.js
  app/steps/ui/declaration/template.html
  test/component/testDeclarationPageMultipleApplicants.js
  test/data/summary-executors.json
  test/unit/testDeclaration.js
Labels: bau, ns:probate-frontend-pr-521
