Repository hmcts/probate-frontend, pull requests merged in 2018-11, with the labels that each got.

#424 Added AKS code
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  infrastructure/main.tf
  kubernetes/.lint.yml
  kubernetes/README.md
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
Labels: ns:probate-frontend-pr-424

#433 PRO-4072: update AD information
  app/config.js
  app/resources/en/translation/common.json
  test/config.js
Labels: ns:probate-frontend-pr-433

#451 Pro 3983 ios session lost
  app/config.js
  package.json
Labels: ns:probate-frontend-pr-451

#450 dr test 123 test
  app/config.js
Labels: ns:probate-frontend-pr-450

#440 PRO-3555: Thank You page
  app/assets/sass/application-common.scss
  app/config.js
  app/resources/en/translation/thankyou.json
  app/routes.js
  app/steps/ui/thankyou/index.js
  app/steps/ui/thankyou/template.html
  test/component/testThankYouPage.js
  test/service-stubs/submit.js
  test/unit/testThankYouPage.js
Labels: ns:probate-frontend-pr-440

#456 Prave pro 3966 msh test
  app/config.js
  app/featureToggles.js
  app/steps/ui/applicant/alias/index.js
  app/steps/ui/applicant/aliasreason/index.js
  app/steps/ui/declaration/index.js
  app/steps/ui/executors/currentname/index.js
  app/steps/ui/executors/currentnamereason/index.js
  app/steps/ui/summary/includes/executors.njk
  app/steps/ui/summary/index.js
  app/utils/FormatName.js
  kubernetes/config.aat.yaml
  test/component/applicant/testAlias.js
  test/component/applicant/testAliasReason.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorCurrentNameReason.js
  test/component/summary/testExecutorsSection.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/data/complete-form-multipleapplicants.json
  test/data/summary-executors.json
  test/unit/testApplicantAlias.js
  test/unit/testApplicantAliasReason.js
  test/unit/testDeclaration.js
  test/unit/testExecutorCurrentName.js
  test/unit/testFeatureToggle.js
  test/unit/testFormatName.js
  test/unit/testSubmitData.js
  test/unit/testSummary.js
Labels: ns:probate-frontend-pr-456

#467 PRO-3897: amend gross400/net400 content on iht-paper
  app/resources/en/translation/iht/paper.json
Labels: bau, ns:probate-frontend-pr-467
