Repository hmcts/probate-frontend, pull requests merged in 2019-05, with the labels that each got.

#730 test the pipeline
  Jenkinsfile_CNP
Labels: ns:probate-frontend-pr-730

#735 commit demosidam changes to master
  infrastructure/demo.tfvars
Labels: ns:probate-frontend-pr-735

#738 PRO-5376: Fix to not clear case state if undefined.
  app/steps/ui/payment/status/index.js
  test/unit/testPaymentStatus.js
Labels: ns:probate-frontend-pr-738

#736 PRO-5377: Display 2 decimals for IHT values on CYA and Declaration pages
  app/steps/ui/declaration/index.js
  app/steps/ui/summary/includes/iht.njk
  test/component/summary/testIHTSection.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/data/complete-form-multipleapplicants.json
  test/data/complete-form-undeclared.json
  test/data/complete-form.json
  test/data/ihtOnline.json
  test/data/ihtPaper.json
  test/unit/testSubmitData.js
  test/util/TestWrapper.js
Labels: ns:probate-frontend-pr-736

#729 Pro 5313 stop will left in formdata
  app/steps/ui/screeners/willleft/index.js
  test/unit/screeners/testWillLeft.js
Labels: ns:probate-frontend-pr-729

#748 PRO-2057: Add hidden descriptive text to CYA link
  app/steps/ui/applicant/aliasreason/template.html
  app/steps/ui/executors/currentnamereason/template.html
  app/steps/ui/iht/paper/template.html
  app/steps/ui/tasklist/includes/copies.html
  app/steps/ui/tasklist/includes/deceased.html
  app/steps/ui/tasklist/includes/documents.html
  app/steps/ui/tasklist/includes/executors.html
  app/steps/ui/tasklist/includes/payment.html
  app/steps/ui/tasklist/includes/reviewAndConfirm.html
  app/views/includes/footer_links.html
  app/views/widgets/lists.html
  test/data/legalDeclationHTML.html
Labels: ns:probate-frontend-pr-748

#757 PRO-5262: Add "Feeback" to aria-label attribute
  test/data/legalDeclationHTML.html
Labels: ns:probate-frontend-pr-757

#746 PRO-5383: add | safe to html variable
  app/config.js
  app/utils/CheckAnswersSummaryJSONObjectBuilder.js
  app/utils/LegalDocumentJSONObjectBuilder.js
  app/views/widgets/addresslookup.html
  test/data/legalDeclarationPDF.json
  test/unit/testLegalDocumentJSONObjectBuilder.js
Labels: ns:probate-frontend-pr-746

#774 PRO-5474: Update chart versions and add liveness unit test
  app/config.js
  app/routes.js
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  charts/probate-frontend/values.preview.template.yaml
  test/unit/testliveness.js
Labels: ns:probate-frontend-pr-774

#756 PRO-4796 (ex PRI-72): Spouse Not Applying Reason
  app/journeys/intestacy.js
  app/resources/en/translation/stoppage.json
  app/steps/ui/applicant/spousenotapplyingreason/index.js
  test/component/applicant/testSpouseNotApplyingReason.js
  test/component/testStopPage.js
  test/unit/testSpouseNotApplyingReason.js
Labels: intestacy, ns:probate-frontend-pr-756

#784 Pro 5463 to fixed fix
  app/steps/ui/declaration/index.js
  test/unit/testLiveness.js
Labels: ns:probate-frontend-pr-784

#779 PRO-4798 (ex PRI-73): Did the deceased have any children
  app/journeys/intestacy.js
  app/resources/en/translation/deceased/allchildrenover18.json
  app/resources/en/translation/deceased/anyotherchildren.json
  app/resources/en/translation/stoppage.json
  app/steps/ui/deceased/allchildrenover18/index.js
  app/steps/ui/deceased/allchildrenover18/schema.json
  app/steps/ui/deceased/allchildrenover18/template.html
  test/component/deceased/testAnyChildren.js
  test/component/testStopPage.js
  test/unit/testAnyChildren.js
  test/unit/testliveness.js
Labels: intestacy, ns:probate-frontend-pr-779

#751 PRO-5404 Addittional validation address line 1
  app/core/steps/AddressStep.js
  app/steps/ui/executors/address/index.js
  test/unit/testAddressStep.js
  test/unit/testExecutorAddress.js
Labels: ns:probate-frontend-pr-751

#790 PRO-5508: Amend copy of one answer to Relationship To Deceased
  app/resources/en/translation/applicant/relationshiptodeceased.json
Labels: intestacy, ns:probate-frontend-pr-790

#792 PRO-4799 (ex PRI-75): All Children Over 18
  app/journeys/intestacy.js
  app/resources/en/translation/deceased/allchildrenover18.json
  app/resources/en/translation/deceased/anydeceasedchildren.json
  app/steps/ui/deceased/allchildrenover18/index.js
  app/steps/ui/deceased/anydeceasedchildren/index.js
  app/steps/ui/deceased/anydeceasedchildren/schema.json
  app/steps/ui/deceased/anydeceasedchildren/template.html
  test/component/deceased/testAllChildrenOver18.js
  test/component/deceased/testAnyOtherChildren.js
  test/unit/testAllChildrenOver18.js
  test/unit/testAnyOtherChildren.js
  test/unit/testDeceasedMaritalStatus.js
Labels: intestacy, ns:probate-frontend-pr-792

#760 PRO-4080: Updated frontend to point to submit pr for testing 4080.
  app/config.js
  app/services/Payment.js
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/hmctsdemo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:probate-frontend-pr-760
