Repository hmcts/probate-frontend, pull requests merged in 2019-07, with the labels that each got.

#860 PRO-5718: Rename thankyou to thank-you and tasklist to task-list
  app/config.js
  app/routes.js
  app/steps/ui/tasklist/index.js
  app/steps/ui/thankyou/index.js
  test/unit/testDeceasedDivorcePlace.js
  test/unit/testExecutorAddress.js
  test/unit/testTasklist.js
  test/unit/testThankYouPage.js
  test/unit/testWillCodicils.js
Labels: ns:probate-frontend-pr-860

#864 PRO-5724: Eslint Upgrade
  .eslintrc.js
  app/components/logger.js
  app/core/initSteps.js
  app/routes.js
  app/wrappers/DetectDataChange.js
  package.json
  test/api/addressLookup.js
  test/unit/testPostcodeAddressService.js
  yarn.lock
Labels: ns:probate-frontend-pr-864

#865 update feature toggle
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
Labels: ns:probate-frontend-pr-865

#880 O-1234: e2e
  test/end-to-end/helpers/PuppeteerHelper.js
Labels: ns:probate-frontend-pr-880

#886 PRO-5722: Thank You page content update
  app/resources/en/translation/thankyou.json
Labels: ns:probate-frontend-pr-886

#884 Pro 5740 fix e2e ie11 edge
  test/end-to-end/helpers/JSWait.js
Labels: ns:probate-frontend-pr-884

#889 PRO-5743: Update missed thankyou and tasklist links
  app/resources/en/translation/screeners/startapply.json
  app/steps/ui/copies/summary/template.html
  app/steps/ui/documents/index.js
  app/steps/ui/executors/changemade/template.html
  app/steps/ui/executors/invitesent/template.html
  app/steps/ui/executors/updateinvitesent/template.html
  app/steps/ui/screeners/startapply/template.html
  app/steps/ui/screeners/starteligibility/template.html
  test/unit/testDocumentsPage.js
Labels: ns:probate-frontend-pr-889

#885 PRO-5735: Change extensions of some subtemplates to njk for sonar to ignore
  app/steps/ui/copies/summary/template.html
  app/steps/ui/summary/template.html
  app/steps/ui/tasklist/includes/applicants.njk
  app/steps/ui/tasklist/includes/copies.njk
  app/steps/ui/tasklist/includes/deceased.njk
  app/steps/ui/tasklist/includes/documents.njk
  app/steps/ui/tasklist/includes/executors.njk
  app/steps/ui/tasklist/includes/payment.njk
  app/steps/ui/tasklist/includes/reviewAndConfirm.njk
  app/steps/ui/tasklist/template.html
  app/views/widgets/checkanswer.njk
  package.json
Labels: ns:probate-frontend-pr-885

#895 Pro 5537 fix document remove
  app/assets/javascripts/document-upload.js
  app/middleware/documentUpload.js
  test/unit/testDocumentUploadMiddleware.js
Labels: ns:probate-frontend-pr-895

#901 PRO-5771: reset formdata on change of caseType
  app/steps/ui/screeners/willleft/index.js
  test/unit/screeners/testWillLeft.js
Labels: ns:probate-frontend-pr-901

#896 PRO-5747: remove jquery for cheerio
  app/utils/CheckAnswersSummaryJSONObjectBuilder.js
  app/utils/LegalDocumentJSONObjectBuilder.js
  package.json
  test/unit/testCheckAnswersSummaryJSONObjectBuilder.js
  yarn.lock
Labels: ns:probate-frontend-pr-896

#800 PRO-5075: Return to doc upload page after sign out. Toggle
  app/steps/ui/documentupload/index.js
  app/steps/ui/summary/includes/documentupload.njk
  test/data/complete-form.json
  test/unit/testDocumentUpload.js
  test/unit/testTasklist.js
Labels: ns:probate-frontend-pr-800

#904 PRO-5784: Update the webchat to the latest version with Prod keys
  app.js
  app/config.js
  app/resources/en/translation/common.json
  app/views/includes/scripts.html
  kubernetes/deployment.template.yaml
  package.json
  yarn.lock
Labels: ns:probate-frontend-pr-904

#906 Webchat test keys
  app/config.js
  infrastructure/main.tf
  kubernetes/deployment.template.yaml
Labels: ns:probate-frontend-pr-906

#912 PRO-1234: add env variable to conf file so that tests can be run in s…
  Jenkinsfile_nightly
  test/end-to-end/paths/generic/cookieBanner.js
  test/end-to-end/paths/generic/saveAndCloseLink.js
  test/end-to-end/paths/generic/surveyLink.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate-frontend-pr-912

#902 PRO-5777: Update UK and Overseas copies fee to £1.50
  app/config.js
  app/featureToggles.js
  app/middleware/calculatePaymentFees.js
  app/resources/en/translation/copies/overseas.json
  app/resources/en/translation/copies/start.json
  app/resources/en/translation/copies/uk.json
  app/resources/en/translation/screeners/starteligibility.json
  app/steps/ui/copies/overseas/index.js
  app/steps/ui/copies/overseas/template.html
  app/steps/ui/copies/start/index.js
  app/steps/ui/copies/start/template.html
  app/steps/ui/copies/uk/index.js
  app/steps/ui/copies/uk/template.html
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/screeners/starteligibility/index.js
  app/steps/ui/screeners/starteligibility/template.html
  app/utils/FeesCalculator.js
  package.json
  test/component/copies/testCopiesOverseas.js
  test/component/copies/testCopiesStart.js
  test/component/copies/testCopiesUk.js
  test/component/payment/testPaymentBreakdown.js
  test/component/screeners/testStartEligibilityPage.js
  test/service-stubs/feature-toggles.js
  test/service-stubs/fees-api.js
  test/service-stubs/find-address.js
  test/unit/screeners/testStartEligibility.js
  test/unit/testCopiesOverseas.js
  test/unit/testCopiesStart.js
  test/unit/testCopiesUk.js
  test/unit/testFeesCalculator.js
  test/unit/testPaymentBreakdown.js
  test/unit/testPaymentData.js
  test/unit/testPaymentService.js
  yarn.lock
Labels: ns:probate-frontend-pr-902

#921 Update copies fees keyword for Prod
  app/utils/FeesCalculator.js
Labels: ns:probate-frontend-pr-921

#917 PRO-5831: Fix bug with addresses containing single quotes
  app/views/widgets/addresslookup.html
Labels: ns:probate-frontend-pr-917

#911 PRO-5810: Amend "web chat closed" copy
  app/resources/en/translation/common.json
  app/views/includes/scripts.html
Labels: ns:probate-frontend-pr-911

#920 PRO-5835: Updated to handle quotes in address using probate postcode lookup
  app/components/string-utils.js
  test/unit/testStringUtils.js
Labels: ns:probate-frontend-pr-920

#918 Fix test
  test/unit/testDocumentUploadMiddleware.js
Labels: ns:probate-frontend-pr-918

#890 PRO-5578: Add applicant name to coversheet
  app/services/IntestacyCoverSheetPdf.js
  app/services/ProbateCoverSheetPdf.js
  test/unit/testIntestacyCoverSheetPdfService.js
  test/unit/testProbateCoverSheetPdfService.js
Labels: ns:probate-frontend-pr-890

#913 PRO-5749: add sanitization to journey posts
  app.js
  app/middleware/sanitizeRequestBody.js
  package.json
  test/component/applicant/testApplicantName.js
  test/component/deceased/testDetails.js
  test/component/deceased/testName.js
  test/component/deceased/testOtherNames.js
  test/component/executors/testExecutorsNames.js
  test/unit/testSanatizeRequestBody.js
  yarn.lock
Labels: ns:probate-frontend-pr-913

#927 Pro 5850 upload sot
  app/components/submit-data.js
  app/services/UploadLegalDeclaration.js
  app/steps/ui/declaration/index.js
  test/component/testDeclarationIntestacy.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/data/complete-form-multipleapplicants.json
  test/unit/testDeclarationPost.js
  test/unit/testSubmitData.js
  test/unit/testUploadLegalDeclaration.js
Labels: ns:probate-frontend-pr-927

#932 PRO-5880: Remove copies_fees feature toggle
  app/config.js
  app/featureToggles.js
  app/resources/en/translation/copies/overseas.json
  app/resources/en/translation/copies/start.json
  app/resources/en/translation/copies/uk.json
  app/resources/en/translation/screeners/starteligibility.json
  app/steps/ui/copies/overseas/index.js
  app/steps/ui/copies/overseas/template.html
  app/steps/ui/copies/start/index.js
  app/steps/ui/copies/start/template.html
  app/steps/ui/copies/uk/index.js
  app/steps/ui/copies/uk/template.html
  app/steps/ui/screeners/starteligibility/index.js
  app/steps/ui/screeners/starteligibility/template.html
  app/utils/FeesCalculator.js
  test/component/copies/testCopiesOverseas.js
  test/component/copies/testCopiesStart.js
  test/component/copies/testCopiesUk.js
  test/component/screeners/testStartEligibilityPage.js
  test/service-stubs/feature-toggles.js
  test/unit/screeners/testStartEligibility.js
  test/unit/testCopiesOverseas.js
  test/unit/testCopiesStart.js
  test/unit/testCopiesUk.js
  test/unit/testFeesCalculator.js
Labels: ns:probate-frontend-pr-932
