Repository hmcts/probate-frontend, pull requests merged in 2019-04, with the labels that each got.

#661 PRO-4970: Update Document Upload content
  app/assets/sass/patterns/_document-upload.scss
  app/resources/en/translation/documentupload.json
  app/steps/ui/documentupload/template.html
Labels: ns:probate-frontend-pr-661

#682 Add SIDAM curl
  Jenkinsfile_CNP
Labels: ns:probate-frontend-pr-682

#687 PRO-5112: Address some Sonar issues
  app/steps/ui/declaration/template.html
  app/steps/ui/summary/template.html
  app/steps/ui/thankyou/template.html
  app/views/includes/scripts.html
Labels: ns:probate-frontend-pr-687

#689 stop prod deploy
  Jenkinsfile_CNP
Labels: ns:probate-frontend-pr-689

#696 PRO-5154: Refactor code for SIDAM
  test/config.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/PuppeteerHelper.js
  test/end-to-end/helpers/TestConfigurator.js
Labels: ns:probate-frontend-pr-696

#697 Pro 5154 remove tidam from e2e framework
  test/config.js
  test/end-to-end/helpers/TestConfigurator.js
Labels: ns:probate-frontend-pr-697

#698 PRO-5154: Change Zap to Medium alerts as Information alerts are causi…
  security.sh
Labels: ns:probate-frontend-pr-698

#700 PRO-5169: Skip Intestacy e2e test until further notice
  test/end-to-end/paths/intestacy/intestacyPath.js
  test/end-to-end/paths/intestacy/intestacyPath1.js
Labels: ns:probate-frontend-pr-700

#658 PRO-4902: Increase fields maxlength
  app/assets/sass/application-common.scss
  app/steps/ui/applicant/alias/template.html
  app/steps/ui/applicant/name/template.html
  app/steps/ui/deceased/otherNames/template.html
  app/steps/ui/declaration/template.html
  app/steps/ui/executors/currentname/template.html
  app/steps/ui/executors/names/template.html
  app/views/widgets/checkboxes.html
Labels: ns:probate-frontend-pr-658

#685 PRO-5111: Improvements to the AD block
  app/config.js
  app/resources/en/translation/common.json
  app/views/includes/help_details.html
  test/accessibility/a11yTest.js
  test/component/common/testHelpBlockContent.js
  test/component/deceased/testDivorcePlace.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/testDocumentUpload.js
  test/component/testPinSignIn.js
Labels: ns:probate-frontend-pr-685

#659 PRO-4862: Codicils on Declaration page
  app/resources/en/translation/declaration.json
  app/steps/ui/declaration/index.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/unit/testDeclaration.js
  test/unit/testLegalDocumentJSONObjectBuilder.js
Labels: ns:probate-frontend-pr-659

#691 PRO-5121: Change dl, div and dt/dd to table, tr and th/td
  app/steps/ui/copies/summary/template.html
  app/steps/ui/summary/includes/deceased.njk
  app/steps/ui/summary/includes/executors-applicant.njk
  app/steps/ui/summary/includes/executors-others-details.njk
  app/steps/ui/summary/includes/executors-others-not-applying.njk
  app/steps/ui/summary/includes/executors-others.njk
  app/steps/ui/summary/includes/executors.njk
  app/steps/ui/summary/template.html
  app/views/widgets/checkanswer.html
  test/unit/testCheckAnswersSummaryJSONObjectBuilder.js
Labels: ns:probate-frontend-pr-691

#705 add sidam chart job
  Jenkinsfile_CNP
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  charts/probate-frontend/values.template.yaml
Labels: ns:probate-frontend-pr-705

#715 Pro 4864 update ad dropdown with standard pattern
  app/config.js
  app/resources/en/translation/common.json
  app/views/includes/help_details.html
  test/component/common/testHelpBlockContent.js
  test/component/deceased/testDivorcePlace.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/testDocumentUpload.js
  test/component/testPinSignIn.js
Labels: ns:probate-frontend-pr-715

#724 PRO-0000: correct fees url in sprod.tfvars
  infrastructure/demo.tfvars
  infrastructure/hmctsdemo.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:probate-frontend-pr-724

#712 PRO-4947: Increase maxlength of deceased name to 100
  app/steps/ui/deceased/name/template.html
Labels: ns:probate-frontend-pr-712

#711 PRO-4264: Dealing with estate prune formdata
  app/steps/ui/executors/additionalinvite/index.js
  app/steps/ui/executors/additionalinvite/template.html
  app/steps/ui/executors/address/index.js
  app/steps/ui/executors/contactdetails/index.js
  app/steps/ui/executors/dealingwithestate/index.js
  app/steps/ui/executors/roles/index.js
  app/steps/ui/payment/breakdown/index.js
  test/component/executors/testExecutorsAdditionalInvite.js
  test/component/executors/testExecutorsInvite.js
  test/unit/testExecutorRoles.js
  test/unit/testExecutorsAdditionalInvite.js
  test/unit/testExecutorsContactDetails.js
  test/unit/testExecutorsDealing.js
  test/unit/testExecutorsInvite.js
Labels: ns:probate-frontend-pr-711

#704 Pro 4325 check payment status using ccd reference
  .gitignore
  app/components/submit-data.js
  app/config.js
  app/resources/en/translation/payment/breakdown.json
  app/routes.js
  app/services/Payment.js
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  charts/probate-frontend/values.aat.template.yaml
  charts/probate-frontend/values.template.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/hmctsdemo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  kubernetes/config.aat.yaml
  test/component/payment/testPaymentBreakdown.js
  test/component/payment/testPaymentStatus.js
  test/data/complete-form-multipleapplicants.json
  test/data/complete-form-undeclared.json
  test/data/complete-form.json
  test/unit/testPaymentBreakdown.js
  test/unit/testPaymentService.js
  test/unit/testPaymentStatus.js
  test/unit/testSubmitData.js
  test/unit/testTasklist.js
Labels: ns:probate-frontend-pr-704

#714 PRO-5190: Use 2 decimals for IHT Value / IHT Paper and …
  Jenkinsfile_CNP
  app/resources/en/translation/deceased/valueassetsoutside.json
  app/resources/en/translation/iht/paper.json
  app/resources/en/translation/iht/value.json
  app/steps/ui/deceased/valueassetsoutside/index.js
  app/steps/ui/iht/paper/index.js
  app/steps/ui/iht/paper/schema.json
  app/steps/ui/iht/paper/template.html
  app/steps/ui/iht/value/index.js
  app/steps/ui/iht/value/schema.json
  app/steps/ui/iht/value/template.html
  package.json
  test/component/iht/testPaper.js
  test/component/iht/testValue.js
  test/data/complete-form.json
  test/end-to-end/pages/iht/paper.js
  test/unit/testDeceasedValueAssetsOutside.js
  test/unit/testIhtPaper.js
  test/unit/testIhtValue.js
  yarn.lock
Labels: ns:probate-frontend-pr-714
