Repository hmcts/probate-frontend, pull requests merged in 2019-06, with the labels that each got.

#777 Pro 5206 prevent formdata loss
  app/components/security.js
  app/config.js
  test/unit/testSecurity.js
Labels: ns:probate-frontend-pr-777

#802 Feature Toggles stub
  app/config.js
  package.json
  test/service-stubs/feature-toggles.js
  test/service-stubs/persistence.js
Labels: ns:probate-frontend-pr-802

#799 PRO-4797 (ex PRI-77): Any Grandchildren Over 18
  app/journeys/intestacy.js
  app/resources/en/translation/deceased/anygrandchildrenunder18.json
  app/steps/ui/deceased/anygrandchildrenunder18/index.js
  test/component/deceased/testAnyGrandchildrenUnder18.js
  test/unit/testAnyGrandchildrenUnder18.js
Labels: intestacy, ns:probate-frontend-pr-799

#797 PRO-5270: Add role attribute to IHT Paper radio buttons
  app/steps/ui/iht/paper/template.html
Labels: ns:probate-frontend-pr-797

#782 PRO-5263: AD email link tabindex
  app/resources/en/translation/common.json
Labels: ns:probate-frontend-pr-782

#806 PRO-5269: Service name link
  app/views/includes/propositional_navigation.html
Labels: ns:probate-frontend-pr-806

#805 PRO-5273: CCD Case Id VoiceOver
  app/steps/ui/thankyou/index.js
  app/steps/ui/thankyou/template.html
  test/component/testThankYouPage.js
  test/unit/testThankYouPage.js
Labels: ns:probate-frontend-pr-805

#810 PRO-4776: Intestacy Task List
  app/journeys/intestacy.js
  app/journeys/probate.js
  app/resources/en/translation/tasklist.json
  app/steps/ui/applicant/relationshiptodeceased/index.js
  app/steps/ui/tasklist/includes/applicants.html
  app/steps/ui/tasklist/includes/copies.html
  app/steps/ui/tasklist/index.js
  app/steps/ui/tasklist/template.html
  package.json
  test/component/testTasklistPage.js
  test/data/complete-form.json
  test/unit/testTasklist.js
Labels: intestacy

#778 PRO-5216: Replicate caveat fix
  app/middleware/lockPaymentAttempt.js
  app/routes.js
  app/steps/ui/payment/breakdown/index.js
  test/unit/testLockPaymentAttemptMiddleware.js
Labels: ns:probate-frontend-pr-778

#817 PRO-5599: Add word to thank you page
  app/resources/en/translation/thankyou.json
Labels: ns:probate-frontend-pr-817

#819 PRO-5073: Add hint to iht screener
  app/resources/en/translation/screeners/ihtcompleted.json
  app/steps/ui/screeners/ihtcompleted/template.html
Labels: ns:probate-frontend-pr-819

#808 Pro 4081 remove feature toggle doc upload
  app/config.js
  app/featureToggles.js
  app/journeys/intestacy.js
  app/journeys/probate.js
  app/resources/en/translation/documents.json
  app/steps/ui/deceased/address/index.js
  app/steps/ui/documents/index.js
  app/steps/ui/documents/template.html
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  test/component/deceased/testAddress.js
  test/component/testDocumentsPage.js
  test/unit/testDeceasedAddress.js
  test/unit/testDocumentsPage.js
  test/unit/testSummary.js
Labels: ns:probate-frontend-pr-808

#824 Further Document Upload FT cleanup
  test/component/deceased/testAddress.js
  test/component/summary/testDocumentUploadSection.js
  test/component/summary/testSummary.js
  test/component/testDocumentUpload.js
  test/component/testDocumentsPage.js
  test/unit/testDeceasedAddress.js
  test/unit/testFeatureToggle.js
Labels: ns:probate-frontend-pr-824

#823 PRO-4741: Web Chat
  app.js
  app/assets/javascripts/hmcts-webchat-busHandler.js
  app/assets/sass/application-common.scss
  app/config.js
  app/core/steps/Step.js
  app/featureToggles.js
  app/resources/en/translation/common.json
  app/steps/ui/copies/summary/index.js
  app/steps/ui/copies/summary/template.html
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  app/utils/FeatureToggle.js
  app/views/includes/help_details.html
  app/views/includes/scripts.html
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  kubernetes/deployment.template.yaml
  package.json
  test/unit/screeners/testApplicantExecutor.js
  test/unit/screeners/testDeathCertificate.js
  test/unit/screeners/testDeceasedDomicile.js
  test/unit/screeners/testDiedAfterOctober2014.js
  test/unit/screeners/testIhtCompleted.js
  test/unit/screeners/testMentalCapacity.js
  test/unit/screeners/testOtherApplicants.js
  test/unit/screeners/testRelatedToDeceased.js
  test/unit/screeners/testWillLeft.js
  test/unit/screeners/testWillOriginal.js
  test/unit/testCopiesOverseas.js
  test/unit/testCopiesUk.js
  test/unit/testDeceasedAddress.js
  test/unit/testDeceasedAlias.js
  test/unit/testEligibilityValidationStep.js
  test/unit/testExecutorsAdditionalInviteSent.js
  test/unit/testFeatureToggle.js
  test/unit/testWillCodicils.js
  test/unit/testWillCodicilsNumber.js
  yarn.lock
Labels: ns:probate-frontend-pr-823

#830 added cross browser testing sh script
  bin/run-crossbrowser-tests.sh
  package.json
Labels: ns:probate-frontend-pr-830

#834 Webchat update to 0.1.20
  app/assets/javascripts/hmcts-webchat-busHandler.js
  app/views/includes/scripts.html
  package.json
  yarn.lock
Labels: ns:probate-frontend-pr-834

#840 Increase CPU default for PRs
  charts/probate-frontend/values.yaml
Labels: ns:probate-frontend-pr-840

#820 PRO-5560: test for executors before deleting addresses
  app/steps/ui/copies/uk/index.js
Labels: ns:probate-frontend-pr-820

#848 Upgrade webchat to 0.1.21
  app/views/includes/scripts.html
  package.json
  yarn.lock
Labels: ns:probate-frontend-pr-848

#835 PRO-4771: Intestacy CYA
  app/resources/en/translation/applicant/spousenotapplyingreason.json
  app/resources/en/translation/deceased/allchildrenover18.json
  app/resources/en/translation/deceased/anychildren.json
  app/resources/en/translation/deceased/anydeceasedchildren.json
  app/resources/en/translation/deceased/anyotherchildren.json
  app/resources/en/translation/deceased/maritalstatus.json
  app/resources/en/translation/summary.json
  app/steps/ui/applicant/nameasonwill/index.js
  app/steps/ui/applicant/relationshiptodeceased/index.js
  app/steps/ui/deceased/anychildren/index.js
  app/steps/ui/deceased/anydeceasedchildren/index.js
  app/steps/ui/deceased/anyotherchildren/index.js
  app/steps/ui/executors/notified/index.js
  app/steps/ui/iht/assetsoutside/index.js
  app/steps/ui/iht/method/index.js
  app/steps/ui/iht/paper/index.js
  app/steps/ui/iht/value/index.js
  app/steps/ui/iht/valueassetsoutside/index.js
  app/steps/ui/summary/includes/applicants.njk
  app/steps/ui/summary/includes/deceased.njk
  app/steps/ui/summary/includes/documentupload.njk
  app/steps/ui/summary/includes/executors-applicant.njk
  app/steps/ui/summary/includes/executors-others-details.njk
  app/steps/ui/summary/includes/executors-others-not-applying.njk
  app/steps/ui/summary/includes/executors-others.njk
  app/steps/ui/summary/includes/executors.njk
  app/steps/ui/summary/includes/iht.njk
  app/steps/ui/summary/includes/will.njk
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  app/steps/ui/will/codicils/index.js
  app/utils/CheckAnswersSummaryJSONObjectBuilder.js
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  test/component/applicant/testSpouseNotApplyingReason.js
  test/component/deceased/testAllChildrenOver18.js
  test/component/deceased/testAnyDeceasedChildren.js
  test/component/summary/testApplicantsSection.js
  test/component/summary/testExecutorsSection.js
  test/component/summary/testSummary.js
  test/data/applicants.json
  test/unit/testAllChildrenOver18.js
  test/unit/testAnyChildren.js
  test/unit/testAnyDeceasedChildren.js
  test/unit/testAnyGrandchildrenUnder18.js
  test/unit/testAnyOtherChildren.js
  test/unit/testCheckAnswersSummaryJSONObjectBuilder.js
  test/unit/testDeceasedName.js
  test/unit/testIhtMethod.js
  test/unit/testIhtPaper.js
  test/unit/testIhtValue.js
  test/unit/testIhtValueAssetsOutside.js
  test/unit/testPaymentBreakdown.js
  test/unit/testRelationshipToDeceased.js
  test/unit/testSummary.js
  test/unit/testWillCodicils.js
Labels: intestacy, ns:probate-frontend-pr-835

#847 PRO-5272: Address accessibility issues on Payment Breakdown page
  app/steps/ui/payment/breakdown/template.html
Labels: ns:probate-frontend-pr-847

#822 PRO-4775 Intestacy definition updates
  app/components/submit-data.js
  app/config.js
  app/utils/MaritalStatusEnum.js
  app/utils/RelationshipToTheDeceasedEnum.js
  app/utils/SpouseNotApplyingEnum.js
  test/unit/testMaritalStatusEnum.js
  test/unit/testRelationshipToDeceasedEnum.js
  test/unit/testSpouseNotApplyingEnum.js
Labels: ns:probate-frontend-pr-822

#859 update token2
  infrastructure/main.tf
Labels: ns:probate-frontend-pr-859

#828 PRO-4779: Intestacy Documents page
  app/journeys/intestacy.js
  app/resources/en/translation/documents.json
  app/steps/ui/documents/index.js
  app/steps/ui/documents/template.html
  test/component/testDocumentsPage.js
  test/unit/screeners/testApplicantExecutor.js
  test/unit/screeners/testDeathCertificate.js
  test/unit/screeners/testDeceasedDomicile.js
  test/unit/screeners/testDiedAfterOctober2014.js
  test/unit/screeners/testIhtCompleted.js
  test/unit/screeners/testMentalCapacity.js
  test/unit/screeners/testOtherApplicants.js
  test/unit/screeners/testRelatedToDeceased.js
  test/unit/screeners/testWillLeft.js
  test/unit/screeners/testWillOriginal.js
  test/unit/testAddressLookup.js
  test/unit/testCopiesOverseas.js
  test/unit/testCopiesUk.js
  test/unit/testDeceasedAddress.js
  test/unit/testDeceasedAlias.js
  test/unit/testDocumentsPage.js
  test/unit/testEligibilityValidationStep.js
  test/unit/testExecutorsAdditionalInvite.js
  test/unit/testExecutorsAdditionalInviteSent.js
  test/unit/testExecutorsContactDetails.js
  test/unit/testInvite.js
  test/unit/testRemoveInvitedExecutor.js
  test/unit/testSecurity.js
  test/unit/testSetJourney.js
  test/unit/testWillCodicils.js
  test/unit/testWillCodicilsNumber.js
Labels: intestacy, ns:probate-frontend-pr-828
