Repository hmcts/probate-frontend, pull requests merged in 2019-03, with the labels that each got.

#620 Pri 123 pact frontend
  Jenkinsfile_CNP
  app/config.js
  app/services/IntestacySubmitData.js
  package.json
  test/contract/pact/FormDataPaClient.spec.js
  test/contract/pact/IntestacyFormDataClient.spec.js
  test/contract/pact/IntestacySubmitDataClient.spec.js
  test/contract/publish/PublishPacts.js
  test/unit/testIntestacySubmitDataService.js
  yarn.lock
Labels: ns:probate-frontend-pr-620

#623 PRO-3956: Delete addresses array once all executors applying have agr…
  app/steps/ui/copies/uk/index.js
  test/component/copies/testCopiesUk.js
  test/data/copiesUk.json
Labels: ns:probate-frontend-pr-623

#613 PRO-4686: Update to add noscript image for tracking non javascript se…
  app/assets/images/noJS.png
  app/views/includes/scripts.html
Labels: ns:probate-frontend-pr-613

#625 PRO-4629: Updated welsh forms on start eligibility
  app/resources/en/translation/screeners/starteligibility.json
Labels: ns:probate-frontend-pr-625

#635 Fix Start Eligibility page and component test
  app/steps/ui/screeners/starteligibility/template.html
  test/component/screeners/testStartEligibilityPage.js
Labels: ns:probate-frontend-pr-635

#626 PRO-4730: Updated name labels
  app/resources/en/translation/applicant/name.json
  app/resources/en/translation/deceased/name.json
  app/resources/en/translation/deceased/otherNames.json
  app/steps/ui/applicant/name/template.html
  app/steps/ui/deceased/name/template.html
  app/steps/ui/deceased/otherNames/template.html
Labels: ns:probate-frontend-pr-626

#618 [PREVIEW] Remove Terraform remote state
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:probate-frontend-pr-618

#637 PRO-4894: Dynamic deceased name on Assets Overseas page
  app/resources/en/translation/assets/overseas.json
  app/steps/ui/assets/overseas/index.js
  app/steps/ui/assets/overseas/template.html
  app/steps/ui/copies/summary/index.js
  app/steps/ui/copies/summary/template.html
  test/component/assets/testAssetsOverseas.js
  test/unit/testAssetsOverseas.js
Labels: ns:probate-frontend-pr-637

#632 PRO-4886: Create fees_api feature toggle
  app/config.js
  app/featureToggles.js
  test/accessibility/a11yTest.js
Labels: ns:probate-frontend-pr-632

#633 Pro 3779 session not timing out
  Jenkinsfile_CNP
  app.js
  app/components/security.js
  app/components/utils.js
  app/config.js
  app/resources/en/translation/timeout.json
  app/steps/ui/timeout/index.js
  app/steps/ui/timeout/template.html
  charts/probate-frontend/values.aat.template.yaml
  charts/probate-frontend/values.template.yaml
  test/component/testSecurity.js
  test/component/testTimeout.js
  test/end-to-end/pages/screeners/startapply.js
  test/end-to-end/pages/screeners/starteligibility.js
  test/unit/testSecurity.js
  test/unit/testTimeout.js
Labels: do not merge, ns:probate-frontend-pr-633

#650 PRO-4687: Hard-code fees on Start Eligibility page
  app/resources/en/translation/screeners/starteligibility.json
  app/steps/ui/screeners/starteligibility/index.js
  app/steps/ui/screeners/starteligibility/template.html
  test/component/screeners/testStartEligibilityPage.js
  test/unit/screeners/testStartApply.js
  test/unit/screeners/testStartEligibility.js
  test/unit/testStartApply.js
  test/unit/testStartEligibility.js
Labels: ns:probate-frontend-pr-650

#629 PRO-4626: Display copies fees on UK Copies and Overseas Copies pages …
  app/resources/en/translation/assets/overseas.json
  app/resources/en/translation/copies/overseas.json
  app/resources/en/translation/copies/uk.json
  app/steps/ui/assets/overseas/template.html
  app/steps/ui/copies/overseas/index.js
  app/steps/ui/copies/overseas/template.html
  app/steps/ui/copies/uk/index.js
  app/steps/ui/copies/uk/template.html
  app/steps/ui/deceased/assetsoutside/index.js
  app/steps/ui/pin/signin/template.html
  test/component/copies/testCopiesOverseas.js
  test/component/copies/testCopiesUk.js
  test/unit/testCopiesOverseas.js
  test/unit/testCopiesUk.js
Labels: ns:probate-frontend-pr-629

#646 PRO-4040: Deceased alias fix post handler
  app/steps/ui/deceased/alias/index.js
  test/unit/testDeclaration.js
Labels: ns:probate-frontend-pr-646

#644 PRO-4631: Amended inheritance paper labels
  app/resources/en/translation/iht/paper.json
Labels: ns:probate-frontend-pr-644

#642 PRO-4907: Whitelisted footer links outside IDAM
  app/config.js
Labels: ns:probate-frontend-pr-642

#667 PRO-5005: Test SIDAM
  charts/probate-frontend/values.aat.template.yaml
Labels: ns:probate-frontend-pr-667

#680 Update Dockerfile
  Dockerfile
Labels: ns:probate-frontend-pr-680
