Repository hmcts/probate-frontend, pull requests merged in 2019-09, with the labels that each got.

#952 PRO-6048: Remove IntestacyQuestions and Webchat feature toggles
  app/config.js
  app/featureToggles.js
  app/journeys/intestacy.js
  app/journeys/probate.js
  app/resources/en/translation/stoppage.json
  app/steps/ui/screeners/willleft/index.js
  app/views/includes/help_details.html
  app/views/includes/scripts.html
  test/accessibility/a11yTest.js
  test/component/applicant/testAdoptionPlace.js
  test/component/applicant/testRelationshipToDeceased.js
  test/component/applicant/testSpouseNotApplyingReason.js
  test/component/deceased/testAnyChildren.js
  test/component/deceased/testAnyDeceasedChildren.js
  test/component/deceased/testAnyGrandchildrenUnder18.js
  test/component/deceased/testAnyOtherChildren.js
  test/component/deceased/testDetails.js
  test/component/deceased/testDivorcePlace.js
  test/component/deceased/testMaritalStatus.js
  test/component/iht/testAssetsOutside.js
  test/component/iht/testValueAssetsOutside.js
  test/component/screeners/testDiedAfterOctober2014.js
  test/component/screeners/testOtherApplicants.js
  test/component/screeners/testRelatedToDeceased.js
  test/component/screeners/testWillLeft.js
  test/component/summary/testApplicantsSection.js
  test/component/summary/testSummary.js
  test/component/testDeclarationIntestacy.js
  test/component/testStopPage.js
  test/service-stubs/feature-toggles.js
  test/unit/screeners/testApplicantExecutor.js
  test/unit/screeners/testDeathCertificate.js
  test/unit/screeners/testDeceasedDomicile.js
  test/unit/screeners/testDiedAfterOctober2014.js
  test/unit/screeners/testIhtCompleted.js
  test/unit/screeners/testMentalCapacity.js
  test/unit/screeners/testOtherApplicants.js
  test/unit/screeners/testRelatedToDeceased.js
  test/unit/screeners/testWillLeft.js
  test/unit/screeners/testWillOriginal.js
  test/unit/testCopiesOverseas.js
  test/unit/testCopiesUk.js
  test/unit/testDeceasedAddress.js
  test/unit/testDeceasedAlias.js
  test/unit/testEligibilityValidationStep.js
  test/unit/testExecutorsAdditionalInviteSent.js
  test/unit/testFeatureToggle.js
  test/unit/testSoftStops.js
  test/unit/testSummary.js
  test/unit/testWillCodicils.js
  test/unit/testWillCodicilsNumber.js
Labels: ns:probate-frontend-pr-952

#965 Pro 5526 fix accent bug
  app/services/InviteLink.js
  charts/probate-frontend/values.preview.template.yaml
  test/unit/testInviteLinkService.js
Labels: ns:probate-frontend-pr-965

#971 PRO-6173: Revert webdriver version to v4 as this is the version compa…
  package.json
  yarn.lock
Labels: ns:probate-frontend-pr-971

#983 PRO-6099: Fix address forms bugs
  app/assets/javascripts/form-polyfill.js
  app/core/steps/AddressStep.js
  app/steps/action/addAlias/schema.json
  app/steps/action/addressLookup/index.js
  app/steps/action/addressLookup/schema.json
  app/steps/action/removeAlias/schema.json
  app/steps/ui/applicant/address/schema.json
  app/steps/ui/applicant/address/template.html
  app/steps/ui/applicant/alias/schema.json
  app/steps/ui/applicant/aliasreason/schema.json
  app/steps/ui/applicant/name/schema.json
  app/steps/ui/assets/overseas/schema.json
  app/steps/ui/coapplicant/declaration/schema.json
  app/steps/ui/copies/overseas/schema.json
  app/steps/ui/copies/uk/schema.json
  app/steps/ui/deceased/address/schema.json
  app/steps/ui/deceased/address/template.html
  app/steps/ui/deceased/married/schema.json
  app/steps/ui/deceased/name/schema.json
  app/steps/ui/deceased/otherNames/schema.json
  app/steps/ui/declaration/schema.json
  app/steps/ui/documents/schema.json
  app/steps/ui/executors/address/index.js
  app/steps/ui/executors/address/schema.json
  app/steps/ui/executors/address/template.html
  app/steps/ui/executors/allalive/schema.json
  app/steps/ui/executors/applying/schema.json
  app/steps/ui/executors/contactdetails/schema.json
  app/steps/ui/executors/currentname/schema.json
  app/steps/ui/executors/currentnamereason/schema.json
  app/steps/ui/executors/dealingwithestate/schema.json
  app/steps/ui/executors/invite/schema.json
  app/steps/ui/executors/names/schema.json
  app/steps/ui/executors/number/schema.json
  app/steps/ui/executors/updateinvite/schema.json
  app/steps/ui/executors/whendied/schema.json
  app/steps/ui/executors/whodied/schema.json
  app/steps/ui/iht/identifier/schema.json
  app/steps/ui/iht/method/schema.json
  app/steps/ui/iht/paper/schema.json
  app/steps/ui/pin/signin/schema.json
  app/steps/ui/will/codicils/schema.json
  app/steps/ui/will/codicilsnumber/schema.json
  app/views/includes/error_summary.html
  app/views/includes/two_thirds_form.html
  app/views/widgets/addresslookup.html
  app/views/widgets/fielderror.html
  package.json
  sonar-project.properties
  test/unit/executors/testExecutorAddress.js
  test/unit/testAddressStep.js
Labels: ns:probate-frontend-pr-983

#987 Fix broken nightly
  test/end-to-end/helpers/SauceLabsReportingHelper.js
Labels: ns:probate-frontend-pr-987

#988 PRO-5208: Accessibility page
  app/config.js
  app/resources/en/translation/common.json
  app/resources/en/translation/static/accessibility.json
  app/steps/ui/static/accessibility/index.js
  app/steps/ui/static/accessibility/template.html
  app/views/includes/footer_links.html
  test/component/static/testAccessibility.js
  test/data/legalDeclationHTML.html
Labels: ns:probate-frontend-pr-988

#991 PRO-6279: Amends to the Accessibility Statement page
  app/config.js
  app/resources/en/translation/static/accessibility.json
  app/steps/ui/static/accessibility/template.html
Labels: ns:probate-frontend-pr-991

#992 PRO-6269: Update jQuery and improve Document Upload page
  app.js
  app/assets/javascripts/document-upload.js
  app/assets/javascripts/jquery-1.11.3.js
  app/steps/ui/documentupload/template.html
  app/views/includes/scripts.html
  package.json
  yarn.lock
Labels: ns:probate-frontend-pr-992

#968 Amends to translation files
  app/resources/en/translation/addressLookup.json
  app/resources/en/translation/applicant/address.json
  app/resources/en/translation/common.json
  app/resources/en/translation/deceased/address.json
  app/resources/en/translation/executors/address.json
  app/resources/en/translation/pin/signin.json
  app/resources/en/translation/static/privacy.json
  app/views/includes/scripts.html
  test/data/copiesUk.json
Labels: ns:probate-frontend-pr-968
