Repository hmcts/probate-frontend, pull requests merged in 2019-11, with the labels that each got.

#1021 PRO-6536: fix case update after pay failed
  app/core/runners/UIStepRunner.js
Labels: ns:probate-frontend-pr-1021

#1023 PRO-6535: Coversheet fix for registry details
  app/services/CoverSheetPdf.js
  app/steps/ui/payment/status/index.js
  test/unit/payment/testPaymentStatus.js
Labels: ns:probate-frontend-pr-1023

#1025 PRO-6539: Content missing in tasklist when more than 1 additional executor is being declared
  app/steps/ui/declaration/index.js
  app/steps/ui/executors/invite/index.js
Labels: ns:probate-frontend-pr-1025

#1028 PRO-6535: Payment success fix
  app/steps/ui/payment/status/index.js
  test/unit/payment/testPaymentStatus.js
Labels: ns:probate-frontend-pr-1028

#1022 PRO-6545: Show "Disagreed" coapplicant declaration status on Tasklist
  Jenkinsfile_CNP
  app/core/steps/Step.js
  app/middleware/multipleApplications.js
  app/resources/en/translation/tasklist.json
  app/routes.js
  app/steps/ui/executors/currentnamereason/index.js
  app/steps/ui/tasklist/includes/reviewAndConfirm.njk
  app/utils/AliasData.js
  test/component/executors/testExecutorCurrentNameReason.js
  test/component/pin/testPinSignIn.js
  test/service-stubs/multipleApplications.js
  test/unit/executors/testExecutorCurrentNameReason.js
  test/unit/middleware/testMultipleApplications.js
Labels: ns:probate-frontend-pr-1022

#1029 PRO-6601: Clear cookie on sign out
  app/components/security.js
  app/config.js
  app/resources/en/translation/screeners/startapply.json
  app/routes.js
  app/steps/ui/signout/index.js
  test/unit/testSignOut.js
Labels: ns:probate-frontend-pr-1029

#1018 PRO-6541: Hide navigation for coapplicant journey
  app/steps/ui/coapplicant/agreepage/template.html
  app/steps/ui/coapplicant/allagreedpage/template.html
  app/steps/ui/coapplicant/declaration/template.html
  app/steps/ui/coapplicant/disagreepage/template.html
  app/steps/ui/coapplicant/startpage/template.html
  app/steps/ui/pin/resend/template.html
  app/steps/ui/pin/sent/template.html
  app/steps/ui/pin/signin/template.html
  app/views/includes/layout.html
Labels: ns:probate-frontend-pr-1018

#1040 update version number
  charts/probate-frontend/Chart.yaml
Labels: ns:probate-frontend-pr-1040

#1043 PRO-6548: postcode lookup fix executors cya
  app/steps/ui/executors/address/index.js
Labels: ns:probate-frontend-pr-1043

#1042 PRO-6706: Check for existing session on Redis before setting cookie
  app.js
Labels: ns:probate-frontend-pr-1042

#1033 Add api version for helm chart
  charts/probate-frontend/Chart.yaml
Labels: ns:probate-frontend-pr-1033

#1057 Fix feature toggle version
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
Labels: ns:probate-frontend-pr-1057

#1063 Pro 5714 investigate download issue for cover sheet
  app/config.js
  app/services/Pdf.js
Labels: ns:probate-frontend-pr-1063

#1048 PRO-6765: Pass user login status to all Nunjucks page renderers
  app.js
  app/components/security.js
  app/core/runners/ActionStepRunner.js
  app/core/runners/OptionGetRunner.js
  app/core/runners/RedirectRunner.js
  app/core/runners/UIStepRunner.js
  app/invite.js
  app/middleware/documentDownload.js
  app/routes.js
  app/views/includes/layout.html
Labels: ns:probate-frontend-pr-1048

#1013 PRO-5061: Turn off autocomplete
  app/steps/ui/applicant/address/template.html
  app/steps/ui/deceased/address/template.html
  app/steps/ui/executors/address/template.html
  app/views/widgets/addresslookup.html
Labels: ns:probate-frontend-pr-1013

#1051 PRO-6769: Disable links as doc uploads
  app/assets/javascripts/document-upload.js
Labels: ns:probate-frontend-pr-1051
