Repository hmcts/probate-frontend, pull requests merged in 2019-02, with the labels that each got.

#583 PRO-4734 Add Chart inc Feature Toggle
  Jenkinsfile_CNP
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  charts/probate-frontend/tests/test-service.yaml
  charts/probate-frontend/values.aat.template.yaml
  charts/probate-frontend/values.template.yaml
Labels: ns:probate-frontend-pr-583

#591 revert to AKS in Jenkinsfile
  Jenkinsfile_CNP
Labels: ns:probate-frontend-pr-591

#604 Pro 4569 calculate fees on payment breakdown - from CNP
  Jenkinsfile_CNP
  PRO-4569__initial_refactor_for_fees_api.patch
  app/config.js
  app/core/runners/UIStepRunner.js
  app/middleware/calculatePaymentFees.js
  app/paymentFees.js
  app/resources/en/translation/payment/breakdown.json
  app/routes.js
  app/services/Fees.js
  app/services/FeesLookup.js
  app/services/FeesRegister.js
  app/steps/ui/payment/breakdown/index.js
  app/utils/FeesCalculator.js
  charts/probate-frontend/values.aat.template.yaml
  charts/probate-frontend/values.template.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/hmctsdemo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  package.json
  test/component/payment/testPaymentBreakdown.js
  test/data/paymentfees/paymentfees-response.json
  test/data/paymentfees/paymentfeeslookup-response.json
  test/service-stubs/fees-api.js
  test/unit/testFees.js
  test/unit/testFeesCalculator.js
  test/unit/testFeesLookup.js
  test/unit/testPaymentBreakdown.js
  yarn.lock
Labels: ns:probate-frontend-pr-604

#605 PRO-4582: Content changes
  app/resources/en/translation/documentupload.json
Labels: ns:probate-frontend-pr-605

#606 Pro 4523 limit freetext address boxes
  app/steps/ui/applicant/address/schema.json
  app/steps/ui/deceased/address/schema.json
  app/steps/ui/executors/address/schema.json
  test/component/applicant/testAddress.js
  test/component/deceased/testAddress.js
  test/component/executors/testExecutorsAddress.js
Labels: ns:probate-frontend-pr-606

#611 set up probate frontend security scan
  Jenkinsfile_nightly
  bin/run-functional-tests.sh
  functional-output/.gitkeep
  security.sh
Labels: ns:probate-frontend-pr-611
