Repository hmcts/probate-frontend, pull requests merged in 2020-03, with the labels that each got.

#1126 PRO-7053: Remove duplicate content
  app/steps/ui/tasklist/includes/reviewAndConfirm.njk
Labels: ns:probate, rel:probate-frontend-pr-1126

#1130 PRO-6072: Prompt user for execs middle names
  app/resources/cy/translation/executors/currentname.json
  app/resources/cy/translation/executors/names.json
  app/resources/en/translation/executors/currentname.json
  app/resources/en/translation/executors/names.json
  app/steps/ui/executors/currentname/template.html
  app/steps/ui/executors/names/template.html
Labels: ns:probate, rel:probate-frontend-pr-1130

#1133 PRO-5079: Only one H1 on Declaration and Coapplicant Declaration pages
  app/steps/ui/coapplicant/declaration/template.html
  app/steps/ui/declaration/template.html
Labels: ns:probate, rel:probate-frontend-pr-1133

#1134 PRO-7090: IDs for PDF download links on Declaration page
  app/steps/ui/declaration/includes/download.html
  app/steps/ui/declaration/template.html
Labels: ns:probate, rel:probate-frontend-pr-1134

#1137 PRO-6919: Fix PIN resend
  app/steps/ui/pin/resend/index.js
  test/component/pin/testPinResend.js
Labels: ns:probate, rel:probate-frontend-pr-1137

#1138 PRO-7120: Fix Intestacy Declaration bugs
  app/resources/cy/translation/declaration.json
  app/resources/en/translation/declaration.json
  app/utils/IntestacyDeclarationFactory.js
  test/component/testDeclarationIntestacy.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/unit/utils/testIntestacyDeclarationFactory.js
Labels: ns:probate, rel:probate-frontend-pr-1138

#1132 PRO-6764: Disable Continue button on last screening questions
  app/assets/javascripts/disable-submit.js
  app/steps/ui/screeners/mentalcapacity/template.html
  app/steps/ui/screeners/otherapplicants/template.html
  app/views/includes/two_thirds_form.html
Labels: ns:probate, rel:probate-frontend-pr-1132

#1140 Update to node 12
  .travis.yml
  Dockerfile
  docker-compose.yml
  infrastructure/main.tf
  package.json
Labels: ns:probate, rel:probate-frontend-pr-1140

#1093 PRO-6900: Check journey type
  app/config.js
  app/journeyCheck.js
  app/middleware/journeyCheck.js
  app/routes.js
  test/accessibility/a11yTest.js
  test/component/applicant/testAdoptionPlace.js
  test/component/applicant/testAlias.js
  test/component/applicant/testAliasReason.js
  test/component/applicant/testNameAsOnWill.js
  test/component/applicant/testRelationshipToDeceased.js
  test/component/applicant/testSpouseNotApplyingReason.js
  test/component/deceased/testAllChildrenOver18.js
  test/component/deceased/testAnyChildren.js
  test/component/deceased/testAnyDeceasedChildren.js
  test/component/deceased/testAnyGrandchildrenUnder18.js
  test/component/deceased/testAnyOtherChildren.js
  test/component/deceased/testDetails.js
  test/component/deceased/testDivorcePlace.js
  test/component/deceased/testDoB.js
  test/component/deceased/testDoD.js
  test/component/deceased/testMaritalStatus.js
  test/component/deceased/testMarried.js
  test/component/deceased/testName.js
  test/component/executors/testChangeMade.js
  test/component/executors/testExecutorAlias.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorCurrentNameReason.js
  test/component/executors/testExecutorsAdditionalInvite.js
  test/component/executors/testExecutorsAdditionalInviteSent.js
  test/component/executors/testExecutorsAddress.js
  test/component/executors/testExecutorsAllAlive.js
  test/component/executors/testExecutorsApplying.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsDealing.js
  test/component/executors/testExecutorsInvite.js
  test/component/executors/testExecutorsInvitesSent.js
  test/component/executors/testExecutorsNames.js
  test/component/executors/testExecutorsNumber.js
  test/component/executors/testExecutorsOtherNames.js
  test/component/executors/testExecutorsUpdateInvite.js
  test/component/executors/testExecutorsUpdateInviteSent.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testExecutorsWhoDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/iht/testAssetsOutside.js
  test/component/iht/testValueAssetsOutside.js
  test/component/will/testWillCodicils.js
  test/component/will/testWillCodicilsNumber.js
  test/data/complete-form-undeclared.json
  test/unit/middleware/testJourneyCheck.js
Labels: ns:probate, ns:probate-frontend-pr-1093, rel:probate-frontend-pr-1093

#1147 Cleanup chart + properties volume for secrets
  .editorconfig
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  app/setupSecrets.js
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  charts/probate-frontend/tests/test-service.yaml
  charts/probate-frontend/values.aat.template.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  infrastructure/.gitignore
  infrastructure/main.tf
  infrastructure/variables.tf
  kubernetes/.lint.yml
  kubernetes/README.md
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  package.json
  server.js
  test/unit/testSetupSecrets.js
  yarn.lock
Labels: ns:probate, rel:probate-frontend-pr-1147

#1151 Add aadidentityname
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.yaml
Labels: ns:probate, rel:probate-frontend-pr-1151

#1150 PRO-5741: amendment for singleexecutorsPath
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, rel:probate-frontend-pr-1150

#1152 Fix redis password mapping
  app/setupSecrets.js
  test/unit/testSetupSecrets.js
Labels: ns:probate, rel:probate-frontend-pr-1152

#1154 Enabling AKS staging and disabling on AAT
  Jenkinsfile_CNP
Labels: ns:probate, rel:probate-frontend-pr-1154

#1155 Upgrade vulnerable dependencies and nightly test url
  Jenkinsfile_nightly
  yarn.lock
Labels: ns:probate, rel:probate-frontend-pr-1155

#1156 fix secret mapping
  app/setupSecrets.js
  test/unit/testSetupSecrets.js
Labels: ns:probate, rel:probate-frontend-pr-1156

#1157 PRO-5741: Fix singleExecutorsPath to work with Win10 IE11
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/WebDriverHelper.js
  test/end-to-end/pages/applicant/address.js
  test/end-to-end/pages/dashboard/dashboard.js
  test/end-to-end/pages/deceased/address.js
  test/end-to-end/pages/executors/address.js
  test/end-to-end/pages/screeners/starteligibility.js
Labels: ns:probate, rel:probate-frontend-pr-1157

#1146 PRO-7178: Disable Continue button on click on Payment Breakdown
  app/steps/ui/payment/breakdown/template.html
Labels: ns:probate, rel:probate-frontend-pr-1146

#1136 PRO-5068: Add new paragraph to Task List
  app/resources/cy/translation/tasklist.json
  app/resources/en/translation/tasklist.json
  app/steps/ui/tasklist/template.html
Labels: ns:probate, rel:probate-frontend-pr-1136

#1125 PRO-6972: Remove Persistence
  README.md
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  docker-compose.yml
  docker/docker-compose-with-idam-local.yml
  docker/docker-compose-with-idam.yml
  docker/jenkins-compose.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/hmctsdemo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  test/service-stubs/orchestrator.js
Labels: ns:probate, rel:probate-frontend-pr-1125

#1164 Pro 5741 fix e2e
  package.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/PuppeteerHelper.js
  test/end-to-end/pages/applicant/nameasonwill.js
  test/end-to-end/pages/coapplicant/agree.js
  test/end-to-end/pages/coapplicant/declaration.js
  test/end-to-end/pages/coapplicant/startPage.js
  test/end-to-end/pages/deceased/anyotherchildren.js
  test/end-to-end/pages/deceased/dob.js
  test/end-to-end/pages/deceased/maritalstatus.js
  test/end-to-end/pages/deceased/otherNames.js
  test/end-to-end/pages/executors/address.js
  test/end-to-end/pages/executors/alias.js
  test/end-to-end/pages/executors/allalive.js
  test/end-to-end/pages/executors/applying.js
  test/end-to-end/pages/executors/contactdetails.js
  test/end-to-end/pages/executors/currentname.js
  test/end-to-end/pages/executors/currentnamereason.js
  test/end-to-end/pages/executors/dealingwithestate.js
  test/end-to-end/pages/executors/invite.js
  test/end-to-end/pages/executors/names.js
  test/end-to-end/pages/executors/notified.js
  test/end-to-end/pages/executors/othername.js
  test/end-to-end/pages/executors/roles.js
  test/end-to-end/pages/executors/whendied.js
  test/end-to-end/pages/executors/whodied.js
  test/end-to-end/pages/language/bilingualgrant.js
  test/end-to-end/pages/pin/signin.js
  test/end-to-end/pages/screeners/otherapplicants.js
  test/end-to-end/pages/screeners/relatedtodeceased.js
  test/end-to-end/pages/signout/signout.js
  test/end-to-end/pages/steps.js
  test/end-to-end/pages/thankyou/thankyou.js
  test/end-to-end/paths/generic/saveAndCloseLink.js
  test/end-to-end/paths/generic/surveyLink.js
  test/end-to-end/paths/intestacy/childPath.js
  test/end-to-end/paths/probate/multipleExecutorsPath.js
  test/end-to-end/paths/probate/singleExecutorsPath.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:probate, rel:probate-frontend-pr-1164

#1169 PRO-5741: upgrade e2e test
  test/end-to-end/pages/deceased/anychildren.js
  test/end-to-end/pages/language/bilingualgrant.js
  test/end-to-end/pages/screeners/deathcertificate.js
  test/end-to-end/paths/generic/survey.js
  test/end-to-end/paths/intestacy/childPath.js
  test/end-to-end/paths/intestacy/spousePath.js
  test/end-to-end/paths/probate/singleExecutorsPath.js
Labels: ns:probate, rel:probate-frontend-pr-1169

#1171 further changes
  test/end-to-end/paths/generic/survey.js
Labels: ns:probate, rel:probate-frontend-pr-1171
