Repository hmcts/probate-frontend, pull requests merged in 2020-10, with the labels that each got.

#1265 DTSPB-536-Add-deathcert-FT
  app/featureToggles.js
  app/journeys/intestacynewdeathcertflow.js
  app/journeys/probatenewdeathcertflow.js
  app/middleware/setJourney.js
  config/default.yaml
  test/unit/middleware/testSetJourney.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1265

#1268 Parameterise test wrapper
  test/util/TestWrapper.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1268

#1270 Dtspb 685 update terrform version
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1270

#1266 Launch darkly working on local e2e
  Jenkinsfile_CNP
  README.md
  test/config.js
  test/end-to-end/helpers/LaunchDarkly.js
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/paths/probate/singleExecutorsPath.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1266

#1278 Close LD stream when tests finished
  test/config.js
  test/end-to-end/helpers/TestConfigurator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1278

#1264 Dtspb 533 new deathcert flow1
  app/core/steps/EligibilityValidationStep.js
  app/journeys/probatenewdeathcertflow.js
  app/middleware/multipleApplications.js
  app/resources/cy/translation/screeners/deathcertificateinenglish.json
  app/resources/cy/translation/screeners/deathcertificatetranslation.json
  app/resources/cy/translation/stoppage.json
  app/resources/en/translation/screeners/deathcertificateinenglish.json
  app/resources/en/translation/screeners/deathcertificatetranslation.json
  app/resources/en/translation/stoppage.json
  app/steps/ui/screeners/deathcertificateinenglish/index.js
  app/steps/ui/screeners/deathcertificateinenglish/schema.json
  app/steps/ui/screeners/deathcertificateinenglish/template.html
  app/steps/ui/screeners/deathcertificatetranslation/index.js
  app/steps/ui/screeners/deathcertificatetranslation/schema.json
  app/steps/ui/screeners/deathcertificatetranslation/template.html
  app/steps/ui/stoppage/index.js
  app/steps/ui/stoppage/template.html
  app/utils/ScreenerValidation.js
  config/default.yaml
  config/dev.yaml
  test/component/testStopPage.js
  test/end-to-end/pages/screeners/deathcertificateinenglish.js
  test/end-to-end/pages/screeners/deathcertificatetranslation.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/probate/singleExecutorsPath.js
  test/unit/core/testEligibilityValidationStep.js
  test/unit/middleware/testMultipleApplications_new_death_cert_flow.js
  test/unit/screeners/testDeathCertificateInEnglish.js
  test/unit/screeners/testDeathCertificateTranslation.js
  test/unit/screeners/testDeathCertificate_new_death_cert_flow.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1264

#1279 Remove test ld sdk key
  config/dev.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1279

#1276 remove pcq health check and pcq health check tests
  app/healthcheck.js
  test/unit/utils/testHealthcheck.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1276

#1283 DTSPB-747 - Enable frontend to run in debug mode cross-platform
  README.md
  package.json
  test/unit/middleware/testCompleteEqualityTask.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1283

#1280 PRO-728: google analytic CSP
  app.js
  app/components/security.js
  app/middleware/completeEqualityTask.js
  app/views/includes/scripts_ga_1.html
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1280

#1287 Dtspb 90 intestacy e2 e tests
  test/config.js
  test/end-to-end/pages/equalityanddiversity/completedpage.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1287
