Repository hmcts/probate-frontend, pull requests merged in 2020-05, with the labels that each got.

#1194 PRO-7201: Add Welsh translations
  app/resources/cy/translation/addAlias.json
  app/resources/cy/translation/applicant/address.json
  app/resources/cy/translation/applicant/name.json
  app/resources/cy/translation/deceased/address.json
  app/resources/cy/translation/deceased/details.json
  app/resources/cy/translation/deceased/dob.json
  app/resources/cy/translation/deceased/dod.json
  app/resources/cy/translation/deceased/name.json
  app/resources/cy/translation/deceased/otherNames.json
  app/resources/cy/translation/executors/address.json
  app/resources/cy/translation/executors/currentname.json
  app/resources/cy/translation/executors/names.json
  app/resources/cy/translation/iht/paper.json
  app/resources/cy/translation/iht/value.json
  app/resources/cy/translation/iht/valueassetsoutside.json
  app/resources/cy/translation/language.json
  app/resources/cy/translation/removeAlias.json
  app/resources/cy/translation/will/codicilsnumber.json
Labels: ns:probate, rel:probate-frontend-pr-1194

#1196 PRO-7373: Update webchat dependency
  package.json
  yarn.lock
Labels: ns:probate, rel:probate-frontend-pr-1196

#1198 LaunchDarkly Performance Improvements
  app.js
  app/components/launch-darkly.js
  app/utils/FeatureToggle.js
  config/default.yaml
  config/test.yaml
  config/testing.yaml
  test/unit/components/testLaunchDarkly.js
  test/unit/utils/testFeatureToggle.js
Labels: ns:probate, rel:probate-frontend-pr-1198

#1202 Change locale to lng for consistency with other services
  app.js
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
Labels: ns:probate, rel:probate-frontend-pr-1202

#1204 Pro 7216 fix authentication when calling pcq
  app/middleware/completeEqualityTask.js
  app/services/FormData.js
  charts/probate-frontend/values.preview.template.yaml
Labels: ns:probate, rel:probate-frontend-pr-1204

#1205 Check PCQ BE health
  app/middleware/completeEqualityTask.js
  test/service-stubs/equalityAndDiversityHealth.js
Labels: ns:probate, rel:probate-frontend-pr-1205
