Repository hmcts/probate-frontend, pull requests merged in 2020-02, with the labels that each got.

#1120 WLA-257: Amend Welsh copy
  Jenkinsfile_CNP
  app/resources/cy/translation/screeners/mentalcapacity.json
Labels: ns:probate, rel:probate-frontend-pr-1120

#1122 PRO-7062: Update fees keywords and move data to config
  Jenkinsfile_CNP
  app/config.js
  app/utils/FeesCalculator.js
Labels: ns:probate, rel:probate-frontend-pr-1122

#1104 PRO-6966: Show submitted cases in green on the dashboard even if prog…
  app/steps/ui/dashboard/template.html
  test/component/testDashboard.js
  test/util/TestWrapper.js
Labels: ns:probate, rel:probate-frontend-pr-1104

#1128 Pro 6988 update legal dec flags on tasklist
  app/middleware/multipleApplications.js
  app/multipleApplications.js
  charts/probate-frontend/values.preview.template.yaml
  test/component/testTasklistPage.js
  test/unit/middleware/testMultipleApplications.js
Labels: ns:probate, rel:probate-frontend-pr-1128

#1102 Pro 6842 amounts to 2 dp
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/breakdown/template.html
  app/steps/ui/payment/status/index.js
  test/unit/payment/testPaymentBreakdown.js
Labels: ns:probate, rel:probate-frontend-pr-1102
