Repository hmcts/probate-frontend, pull requests merged in 2020-12, with the labels that each got.

#1315 Dtspb 893 healthcheck upgrade branch 2
  app.js
  app/healthcheck.js
  app/middleware/completeEqualityTask.js
  app/routes.js
  app/utils/Healthcheck.js
  app/utils/healthOptions.js
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  config/default.yaml
  package.json
  test/smoke/healthcheck.js
  test/unit/testHealthcheck.js
  test/unit/utils/testHealthOptions.js
  test/unit/utils/testHealthcheck.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1315

#1304 Update Node chart
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1304

#1318 Add welsh content
  app/resources/cy/translation/deceased/deathcertificate.json
  app/resources/cy/translation/deceased/diedengorwales.json
  app/resources/cy/translation/deceased/englishforeigndeathcert.json
  app/resources/cy/translation/deceased/foreigndeathcerttranslation.json
  app/resources/cy/translation/documents_new_death_cert_flow.json
  app/resources/cy/translation/screeners/deathcertificate.json
  app/resources/cy/translation/screeners/deathcertificateinenglish.json
  app/resources/cy/translation/screeners/deathcertificatetranslation.json
  app/resources/cy/translation/stoppage.json
  app/resources/en/translation/deceased/deathcertificate.json
  app/resources/en/translation/deceased/foreigndeathcerttranslation.json
  app/resources/en/translation/documents_new_death_cert_flow.json
  app/resources/en/translation/screeners/deathcertificateinenglish.json
  app/resources/en/translation/screeners/deathcertificatetranslation.json
  app/steps/ui/deceased/englishforeigndeathcert/template.html
  test/component/deceased/testDeathCertificate.js
  test/component/deceased/testDiedEngOrWales.js
  test/component/deceased/testEnglishForeignDeathCert.js
  test/component/deceased/testForeignDeathCertTranslation.js
  test/unit/testDocumentsPage_new_death_cert-flow.js
  test/util/TestWrapper.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1318

#1272 PRO-132: New fee register code keyword
  app/featureToggles.js
  app/steps/ui/payment/breakdown/index.js
  app/utils/FeesCalculator.js
  config/default.yaml
  test/unit/utils/testFeesCalculator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1272

#1321 Feature(DTSPB-999): Upgrade crossbrowser dependencies
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  commit-msg.sh
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/SauceLabsReportingHelper.js
  test/end-to-end/helpers/WebDriverHelper.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1321

#1322 DTSPB-999: Fix crossbrowser reporting
  Jenkinsfile_nightly
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1322

#1302 PRO-697: only check co application agree on co-application-agree-page
  app/invite.js
  app/resources/cy/translation/coapplicant/agreepage.json
  app/resources/en/translation/coapplicant/agreepage.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1302

#1325 DTSPB-999: Get crossbrowser tests running on Chrome
  Jenkinsfile_nightly
  config/testing-http-dk.yaml
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/IDAMHelper.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/paths/generic/cookieBanner.test.js
  test/end-to-end/paths/generic/survey.test.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1325

#1330 Dtspb 864 deathcert add form links
  app/resources/cy/translation/documents_new_death_cert_flow.json
  app/resources/cy/translation/stoppage.json
  app/resources/en/translation/documents_new_death_cert_flow.json
  app/resources/en/translation/stoppage.json
  app/steps/ui/documents/template.html
  config/default.yaml
  test/component/testDocumentsPage.js
  test/component/testStopPage.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1330

#1331 DTSPB-1016 get crossbrowser tests more stable and add potential to run on Safari (does not turn Safari on)
  .vscode/launch.json
  bin/run-crossbrowser-tests.sh
  config/testing-http-dk.yaml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/pages/IDAM/signIn.js
  test/end-to-end/pages/copies/summary.js
  test/end-to-end/pages/dashboard/chooseApplication.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1331
