Repository hmcts/probate-frontend, pull requests merged in 2020-06, with the labels that each got.

#1208 PRO-7428: adding data layer script
  app/views/includes/error_summary.html
  app/views/includes/scripts_ga_1.html
Labels: ns:probate, rel:probate-frontend-pr-1208

#1203 PRO-7430: adding header link
  app/assets/sass/patterns/_header.scss
  app/views/includes/layout.html
Labels: ns:probate, rel:probate-frontend-pr-1203

#1211 Hide webchat on Welsh
  app/core/steps/Step.js
  app/views/includes/help_details.html
  app/views/includes/scripts.html
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/requirements.yaml
  test/unit/copies/testCopiesOverseas.js
  test/unit/copies/testCopiesUk.js
  test/unit/core/testEligibilityValidationStep.js
  test/unit/deceased/testDeceasedAddress.js
  test/unit/deceased/testDeceasedAlias.js
  test/unit/executors/testExecutorsAdditionalInviteSent.js
  test/unit/pin/testPinResend.js
  test/unit/pin/testPinSent.js
  test/unit/screeners/testApplicantExecutor.js
  test/unit/screeners/testDeathCertificate.js
  test/unit/screeners/testDeceasedDomicile.js
  test/unit/screeners/testDiedAfterOctober2014.js
  test/unit/screeners/testIhtCompleted.js
  test/unit/screeners/testMentalCapacity.js
  test/unit/screeners/testOtherApplicants.js
  test/unit/screeners/testRelatedToDeceased.js
  test/unit/screeners/testWillLeft.js
  test/unit/screeners/testWillOriginal.js
  test/unit/testDashboard.js
  test/unit/testSummary.js
  test/unit/will/testWillCodicils.js
  test/unit/will/testWillCodicilsNumber.js
Labels: ns:probate, rel:probate-frontend-pr-1211

#1217 PCQ-273: Chart changes
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1217

#1213 PCQ-273: Authorisation of invoking services
  app/middleware/completeEqualityTask.js
  app/setupSecrets.js
  app/steps/ui/equality/createToken.js
  app/steps/ui/equality/index.js
  config/custom-environment-variables.yaml
  config/default.yaml
  test/unit/middleware/testCompleteEqualityTask.js
  test/unit/testEquality.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1213
