Repository hmcts/probate-frontend, pull requests merged in 2020-11, with the labels that each got.

#1297 DTSPB-851 fix for payment api
  docker-compose.yml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1297

#1293 Dtspb 529 new death cert process
  app/featureToggles.js
  app/journeys/intestacynewdeathcertflow.js
  app/journeys/probatenewdeathcertflow.js
  app/middleware/setJourney.js
  app/resources/cy/translation/deceased/deathcertificate.json
  app/resources/cy/translation/deceased/diedengorwales.json
  app/resources/cy/translation/deceased/englishforeigndeathcert.json
  app/resources/cy/translation/deceased/foreigndeathcerttranslation.json
  app/resources/en/translation/deceased/deathcertificate.json
  app/resources/en/translation/deceased/diedengorwales.json
  app/resources/en/translation/deceased/englishforeigndeathcert.json
  app/resources/en/translation/deceased/foreigndeathcerttranslation.json
  app/steps/ui/deceased/deathcertificate/index.js
  app/steps/ui/deceased/deathcertificate/schema.json
  app/steps/ui/deceased/deathcertificate/template.html
  app/steps/ui/deceased/diedengorwales/index.js
  app/steps/ui/deceased/diedengorwales/schema.json
  app/steps/ui/deceased/diedengorwales/template.html
  app/steps/ui/deceased/englishforeigndeathcert/index.js
  app/steps/ui/deceased/englishforeigndeathcert/schema.json
  app/steps/ui/deceased/englishforeigndeathcert/template.html
  app/steps/ui/deceased/foreigndeathcerttranslation/index.js
  app/steps/ui/deceased/foreigndeathcerttranslation/schema.json
  app/steps/ui/deceased/foreigndeathcerttranslation/template.html
  charts/probate-frontend/Chart.yaml
  test/component/deceased/testAddress_new_death_cert_flow.js
  test/component/deceased/testDeathCertificate.js
  test/component/deceased/testDiedEngOrWales.js
  test/component/deceased/testEnglishForeignDeathCert.js
  test/component/deceased/testForeignDeathCertTranslation.js
  test/end-to-end/pages/deceased/deathcertificate.js
  test/end-to-end/pages/deceased/diedengorwales.js
  test/end-to-end/pages/deceased/englishforeigndeathcert.js
  test/end-to-end/pages/deceased/foreigndeathcerttranslation.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/unit/deceased/testDeceasedDeathCertificate.js
  test/unit/deceased/testDeceasedDiedEngOrWales.js
  test/unit/deceased/testEnglishForeignDeathCertificate.js
  test/unit/deceased/testForeignDeathCertTranslation.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1293

#1231 PRO-7887: extra copies for grant and will
  app/resources/cy/translation/copies/overseas.json
  app/resources/cy/translation/copies/uk.json
  app/resources/en/translation/copies/overseas.json
  app/resources/en/translation/copies/uk.json
  app/steps/ui/copies/overseas/template.html
  app/steps/ui/copies/uk/template.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1231

#1301 Dtspb 738 cya page new death cert flow
  app/journeys/intestacynewdeathcertflow.js
  app/steps/ui/summary/includes/deceased.njk
  app/steps/ui/summary/index.js
  app/steps/ui/summary/template.html
  test/component/summary/testDeceasedSection_new_death_cert_flow.js
  test/data/deceased_new_death_cert_flow.json
  test/unit/testSummary.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1301

#1274 Dtspb 666 validate uk mobile phone number
  app/steps/ui/executors/contactdetails/index.js
  app/utils/PhoneNumberValidator.js
  test/unit/utils/testPhoneNumberValidator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1274

#1300 Dtspb 716 send docs death cert flow
  app/resources/cy/translation/documents_new_death_cert_flow.json
  app/resources/cy/translation/thankyou.json
  app/resources/en/translation/documents_new_death_cert_flow.json
  app/resources/en/translation/thankyou.json
  app/steps/ui/documents/index.js
  app/steps/ui/documents/template.html
  app/steps/ui/payment/status/index.js
  app/steps/ui/payment/status/template.html
  app/steps/ui/thankyou/index.js
  app/steps/ui/thankyou/template.html
  app/wrappers/DeathCertificate.js
  app/wrappers/Documents.js
  test/component/payment/testPaymentStatus.js
  test/component/testDocumentsPage.js
  test/component/testThankYouPage.js
  test/unit/payment/testPaymentStatus.js
  test/unit/testDocumentsPage_new_death_cert-flow.js
  test/unit/testThankYouPage.js
  test/unit/wrappers/testDeathCertificate.js
  test/unit/wrappers/testDocumentsWrapper.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1300

#1261 Dtspb 126 payment error solution remove status
  app/steps/ui/payment/status/index.js
  test/unit/payment/testPaymentStatus.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1261

#1309 PRO-931: remove the logger
  app/steps/ui/declaration/index.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1309

#1310 Foreign death cert radio buttons on different lines
  app/steps/ui/deceased/foreigndeathcerttranslation/template.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1310
