Repository hmcts/probate-frontend, pull requests merged in 2020-08, with the labels that each got.

#1227 PRO-7750 changing condition for submitted application.
  app/routes.js
  app/steps/ui/applicant/address/template.html
  app/steps/ui/deceased/address/template.html
  app/steps/ui/executors/address/template.html
  app/views/widgets/addresslookup.html
  app/wrappers/CcdCase.js
  package.json
  test/component/testRedirectToDocuments.js
  test/unit/wrappers/testCcdCaseWrapper.js
  test/util/a11y.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1227

#1233 Pro 7867 add docker compose
  .env
  README.md
  config/default.yaml
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/create-multiple-postgres-database.sh
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1233

#1235 PRO-7920 enable tests
  bin/run-functional-tests.sh
  config/custom-environment-variables.yaml
  functional-output/.gitkeep
  package.json
  test/config.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1235

#1236 Fixing e2e test locally
  README.md
  docker-compose.yml
  test/config.js
  test/end-to-end/helpers/TestConfigurator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1236

#1238 Re-enable launch darkly on the default config, re-instate the dev con…
  .gitignore
  README.md
  app/components/launch-darkly.js
  charts/probate-frontend/values.aat.template.yaml
  charts/probate-frontend/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/dev.yaml
  config/dev_template.yaml
  test/config.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1238

#1230 PRO-7067: use fees looked up for payements
  app/components/payment-data.js
  app/setupSecrets.js
  app/steps/ui/payment/breakdown/index.js
  app/utils/FeesCalculator.js
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  test/component/payment/testPaymentBreakdown.js
  test/unit/components/testPaymentData.js
  test/unit/components/testPaymentFees.js
  test/unit/payment/testPaymentBreakdown.js
  test/unit/utils/testFeesCalculator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1230
