Repository hmcts/probate-frontend, pull requests merged in 2020-09, with the labels that each got.

#1241 enable contract tests in pipeline
  package.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1241

#1243 DTSPB-259 Update routes.js to have perftest
  app/routes.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1243

#1245 load steps at start up rather than on every request
  app/core/initSteps.js
  app/routes.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1245

#1214 Pro 7557 sot dec wording correction
  app/resources/cy/translation/declaration.json
  app/resources/en/translation/declaration.json
  app/utils/ProbateDeclarationFactory.js
  test/unit/utils/testProbateDeclarationFactory.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1214

#1257 Dtspb 181 enable launchdarkly in pr
  charts/probate-frontend/values.preview.template.yaml
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/pages/equalityanddiversity/startpage.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/probate/singleExecutorsPath.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1257

#1250 Pro 7929 unit test reporting original branch
  .eslintignore
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  package.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1250
