Repository hmcts/probate-frontend, pull requests merged in 2020-01, with the labels that each got.

#1094 PRO-6908: Fix bug on Tasklist section 3
  app/wrappers/Executors.js
Labels: ns:probate-frontend-pr-1094

#1092 PRO-6781: Amend Proceedings copy
  app/resources/en/translation/declaration.json
  test/data/legalDeclationHTML.html
  test/data/pacts/probate/invalidNoTitlelegalDeclaration.json
  test/data/pacts/probate/legalDeclaration.json
  test/data/pacts/probate/submitSingleExeDataClinet.json
Labels: ns:probate-frontend-pr-1092

#1097 RO-6603: Removed server leaking info from HTTP response header
  Jenkinsfile_CNP
  iisnode.yml
  web.config
Labels: ns:probate, ns:probate-frontend-pr-1097, rel:probate-frontend-pr-1097

#1098 Release The Prod ...
  Jenkinsfile_CNP
Labels: ns:probate, rel:probate-frontend-pr-1098

#1108 [DO NOT MERGE] WLA-233: Upgrade Pa11y to latest version
  app/assets/javascripts/dropzone.js
  package.json
  test/accessibility/a11yTest.js
  test/util/a11y.js
  yarn.lock
Labels: ns:probate, rel:probate-frontend-pr-1108

#1091 PRO-6672: Intestacy DoD to be on or after 1 Oct 2014
  app/journeys/intestacy.js
  app/resources/en/translation/screeners/diedafteroctober2014.json
  app/resources/en/translation/stoppage.json
  app/steps/ui/deceased/details/index.js
  test/component/deceased/testDetails.js
  test/data/complete-form.json
  test/unit/deceased/testDeceasedDetails.js
  test/unit/testTasklist.js
Labels: ns:probate, ns:probate-frontend-pr-1091, rel:probate-frontend-pr-1091
