Repository hmcts/probate-frontend, pull requests merged in 2021-01, with the labels that each got.

#1338 Run launch darkly config for e2e
  charts/probate-frontend/Chart.yaml
  package.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1338

#1334 DTSPB-1073-Welsh Accessibility Tests
  app/views/includes/head.html
  package.json
  test/accessibility/a11yTest.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1334

#1342 Fix error in diedengorwales page
  test/end-to-end/pages/deceased/diedengorwales.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1342

#1345 Fix intestacy spouse path
  test/end-to-end/pages/tasklist/tasklist.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1345

#1336 DTSPB-1085: Get tests working on Safari
  bin/run-crossbrowser-tests.sh
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/SauceLabsReportingHelper.js
  test/end-to-end/pages/coapplicant/agree.js
  test/end-to-end/pages/coapplicant/startPage.js
  test/end-to-end/pages/dashboard/chooseApplication.js
  test/end-to-end/pages/deceased/assetsoutsideenglandwales.js
  test/end-to-end/pages/deceased/otherNames.js
  test/end-to-end/pages/documents/documents.js
  test/end-to-end/pages/equalityanddiversity/completedpage.js
  test/end-to-end/pages/equalityanddiversity/startpage.js
  test/end-to-end/pages/executors/invite.js
  test/end-to-end/paths/probate/multipleExecutors.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1336

#1347 DTSPB-1170: Add useNewDeathCertFlow to multipleExecutors.js e2e test
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1347

#1353 Add hash to contentSecurityPolicy
  app.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1353

#1355 Add hash
  app.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1355

#1356 Check FT on death-certificate page
  app/featureToggles.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1356

#1348 PRO-895: upgrade the copies welsh translation
  app/resources/cy/translation/copies/overseas.json
  app/resources/cy/translation/copies/uk.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1348

#1226 PRO-7583: updating the new privacy policy addresses and emails
  app/resources/cy/translation/static/privacy.json
  app/resources/en/translation/static/privacy.json
  app/steps/ui/static/privacy/template.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1226

#1366 DTSPB-1306-GOP Intestacy SpouseE2E
  package.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/dashboard/chooseApplication.js
  test/end-to-end/pages/tasklist/tasklist.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1366
