Repository hmcts/probate-frontend, pull requests merged in 2021-11, with the labels that each got.

#1479 DTSPB-2424: Test for expected estates feature toggle
  config/default.yaml
  package.json
  test/api/launchDarkly.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1479

#1486 Correct auth token issue for pcq call
  app/middleware/completeEqualityTask.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1486

#1487 Remove INFO Logs for Fortify
  test/java/build.gradle
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1487

#1490 Adds app insights npm packages to dependencies
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1490

#1492 Dtspb 2454 ee first question
  app/featureToggles.js
  app/journeys/probate.js
  app/resources/cy/translation/iht/estatevalued.json
  app/resources/en/translation/iht/estatevalued.json
  app/steps/ui/deceased/deathcertificate/index.js
  app/steps/ui/iht/estatevalued/index.js
  app/steps/ui/iht/estatevalued/schema.json
  app/steps/ui/iht/estatevalued/template.html
  app/utils/ExceptedEstateDod.js
  config/default.yaml
  test/component/deceased/testDeathCertificate.js
  test/component/iht/testEstateValued.js
  test/unit/iht/testEstateValued.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1492

#1495 DTSPB-1234: added fix for failing CB test
  package.json
  test/end-to-end/helpers/TestConfigurator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1495

#1496 Suppress the failing Dependancy
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1496

#1501 DTSPB-2491 Volume dependency upgrade
  config/testing-http-dk.yaml
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1501
