Repository hmcts/probate-frontend, pull requests merged in 2021-08, with the labels that each got.

#1446 DTSPB-2284 - Upgrade launchdarkly-node-server-sdk 5.13.3 -> 6.2.0
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1446

#1435 DTSPB-1966 - cookie banner
  .vscode/launch.json
  README.md
  app/assets/javascripts/cookie-banner.js
  app/assets/javascripts/cookie-manager.js
  app/assets/javascripts/cookie.js
  app/assets/sass/application-ie8.scss
  app/assets/sass/application.scss
  app/assets/sass/patterns/_cookie-bar.scss
  app/core/runners/UIStepRunner.js
  app/core/steps/Step.js
  app/resources/cy/translation/common.json
  app/resources/cy/translation/static/cookies.json
  app/resources/en/translation/common.json
  app/resources/en/translation/static/cookies.json
  app/steps/ui/static/cookies/index.js
  app/steps/ui/static/cookies/template.html
  app/views/includes/cookie-banner.html
  app/views/includes/error_summary.html
  app/views/includes/layout.html
  app/views/includes/scripts.html
  app/views/includes/scripts_ga_1.html
  package.json
  test/component/static/testCookies.js
  test/component/testCookieBanner.js
  test/data/legalDeclationHTML.html
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/pages/screeners/starteligibility.js
  test/end-to-end/paths/generic/cookieBanner.test.js
  test/unit/static/testCookies.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1435

#1445 DTSPB-2280 - Add specified "secureProtocol" to fix Fortify scan issue
  app.js
  test/java/build.gradle
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1445

#1444 DTSPB-2276 - Bump chart.yaml nodejs version to 2.3.7
  charts/probate-frontend/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1444

#1440 DTSPB-1979-and-DTSPB-2055-avaya-webchat
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  app.js
  app/assets/javascripts/avaya-webchat-2.js
  app/resources/cy/translation/common.json
  app/resources/cy/translation/static/contact.json
  app/resources/en/translation/common.json
  app/resources/en/translation/static/avaya-webchat.json
  app/resources/en/translation/static/contact.json
  app/setupSecrets.js
  app/steps/ui/static/avaya-webchat/template.html
  app/steps/ui/static/contact/template.html
  app/views/includes/avaya-webchat.html
  app/views/includes/help_details.html
  app/views/includes/scripts.html
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  test/component/common/testCommonContent.js
  test/component/deceased/testDivorcePlace.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/pin/testPinSignIn.js
  test/component/static/testContactUs.js
  test/component/testDashboard.js
  test/component/testDocumentUpload.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1440

#1450 DTSPB-2281 - Secure cookie issue
  app/components/security.js
  test/unit/components/testSecurity.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1450
