Repository hmcts/probate-frontend, pull requests merged in 2021-12, with the labels that each got.

#1499 DTSPB-2488: EE legal declaration
  app/resources/cy/translation/declaration.json
  app/resources/en/translation/declaration.json
  app/steps/ui/declaration/includes/estate.html
  app/steps/ui/declaration/index.js
  app/steps/ui/declaration/template.html
  app/utils/ProbateDeclarationFactory.js
  test/component/testDeclarationIntestacy.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/unit/utils/testProbateDeclarationFactory.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1499

#1503 Add ee screener questions to non idam page list
  config/default.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1503

#1509 DTSPB-2430 fix
  app/featureToggles.js
  app/middleware/multipleApplications.js
  app/utils/ScreenerValidation.js
  config/default.yaml
  test/component/screeners/testIhtCompleted.js
  test/unit/screeners/testIhtCompleted.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1509

#1507 Dtspb 2500 move dod ee to env var
  config/custom-environment-variables.yaml
  test/unit/utils/testExceptedEstateDod.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1507

#1513 DTSPB-2430: Fix new user case creation
  app/middleware/multipleApplications.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1513

#1510 DTSPB-2492: Welsh translations
  app/resources/cy/translation/declaration.json
  app/resources/cy/translation/iht/deceasedlatespousecivilpartner.json
  app/resources/cy/translation/iht/estateform.json
  app/resources/cy/translation/iht/estatevalued.json
  app/resources/cy/translation/iht/ihtestatevalues.json
  app/resources/cy/translation/iht/probateestatevalues.json
  app/resources/cy/translation/iht/unusedallowanceclaimed.json
  app/resources/cy/translation/stoppage.json
  app/resources/cy/translation/will/codicilsdamageculpritknown.json
  app/resources/en/translation/iht/estatevalued.json
  app/resources/en/translation/iht/probateestatevalues.json
  app/resources/en/translation/iht/unusedallowanceclaimed.json
  app/resources/en/translation/will/deceasedwrittenwishes.json
  app/steps/ui/iht/estatevalued/template.html
  app/steps/ui/iht/unusedallowanceclaimed/template.html
  test/unit/utils/testProbateDeclarationFactory.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1510

#1515 DTSPB-2492: Welsh translations
  app/resources/cy/translation/iht/deceasedlatespousecivilpartner.json
  app/resources/cy/translation/iht/estateform.json
  app/resources/cy/translation/iht/estatevalued.json
  app/resources/cy/translation/iht/ihtestatevalues.json
  app/resources/cy/translation/iht/probateestatevalues.json
  app/resources/cy/translation/iht/unusedallowanceclaimed.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1515

#1516 DTSPB-2433 estate valued content change
  app/resources/cy/translation/iht/estatevalued.json
  app/resources/en/translation/iht/estatevalued.json
  app/steps/ui/iht/estatevalued/template.html
  config/default.yaml
  test/component/iht/testEstateValued.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1516

#1511 DTSPB-2437 ee intestacy journey
  app/journeys/intestacy.js
  test/component/deceased/testDeathCertificate.js
  test/component/deceased/testEnglishForeignDeathCert.js
  test/component/deceased/testForeignDeathCertTranslation.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1511

#1520 DTSPB-2437: correct intestacy journey
  app/journeys/intestacy.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1520
