Repository hmcts/probate-frontend, pull requests merged in 2022-10, with the labels that each got.

#1714 Dtspb 3032 her majesty changes
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/static/cookies.json
  app/resources/cy/translation/static/privacy.json
  app/resources/cy/translation/static/terms.json
  app/resources/en/translation/static/terms.json
  test/component/static/testTermsAndConditions.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1714

#1708 DTSPB-2977 check for net qualifying being greater than gross or net o…
  app/resources/cy/translation/iht/ihtestatevalues.json
  app/resources/en/translation/iht/ihtestatevalues.json
  app/steps/ui/iht/ihtestatevalues/index.js
  test/component/iht/testIhtEstateValues.js
  test/unit/iht/testIhtEstateValues.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1708

#1712 DTSPB-3006 Renovate dependency update
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1712
