Repository hmcts/probate-frontend, pull requests merged in 2022-06, with the labels that each got.

#1663 DTSPB-2843: Add test
  test/unit/executors/testExecutorsAdditionalInvite.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1663

#1669 DTSPB-2846: move liveness test
  test/component/testLiveness.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1669

#1666 Dtspb 2473 fe logs in ai
  app.js
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1666

#1574 DTSPO-5664: Fix Appinsights Configuration
  app.js
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1574

#1655 DTSPB-2725 screen send docs page if conditions met and add no docs te…
  app/resources/cy/translation/documents.json
  app/resources/en/translation/documents.json
  app/services/CoverSheetPdf.js
  app/utils/DocumentPageUtil.js
  app/wrappers/Applicant.js
  app/wrappers/Deceased.js
  app/wrappers/Documents.js
  charts/probate-frontend/Chart.yaml
  test/component/testDocumentsPage.js
  test/unit/services/coversheet/testCoverSheetNoDocsRequiredPdf.js
  test/unit/services/coversheet/testCoverSheetPdf.js
  test/unit/testDocumentsPage.js
  test/unit/wrappers/documents-wrapper/testDocumentsWrapper.js
  test/unit/wrappers/documents-wrapper/testDocumentsWrapperDocsRequired.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1655

#1678 DTSPB-2885 update got
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1678
