Repository hmcts/probate-frontend, pull requests merged in 2022-02, with the labels that each got.

#1541 DTSPB-2560: update contact hours
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/static/contact/template.html
  app/views/includes/help_details.html
  test/component/common/testCommonContent.js
  test/component/deceased/testDivorcePlace.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/pin/testPinSignIn.js
  test/component/static/testContactUs.js
  test/component/testDashboard.js
  test/component/testDocumentUpload.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1541

#1532 DTSPB-1422: Ensure unique executor emails
  app/resources/cy/translation/executors/contactdetails.json
  app/resources/en/translation/executors/contactdetails.json
  app/steps/ui/executors/contactdetails/index.js
  app/steps/ui/executors/contactdetails/template.html
  app/wrappers/Executors.js
  test/unit/wrappers/testExecutorsWrapper.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1532

#1537 Dtspb 2395 avaya testing
  app.js
  app/assets/javascripts/avaya-webchat-2.js
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/avaya-webchat.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1537

#1550 Dtspb 2586 suppress CVE 2
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1550

#1558 DTSPB-2600: Fix failing dep for probate fe nightly
  bin/run-yarn-audit.sh
  charts/probate-frontend/Chart.yaml
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1558

#1542 enabled tests on nightly
  package.json
  test/end-to-end/paths/generic/cookieBanner.test.js
  test/end-to-end/paths/generic/survey.test.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/other/creditCardPaymentCancellation.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1542

#1543 DTSPB-2534 Call Times 26th Feb
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/static/contact/template.html
  app/views/includes/help_details.html
  package.json
  test/component/common/testCommonContent.js
  test/component/deceased/testDivorcePlace.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/pin/testPinSignIn.js
  test/component/static/testContactUs.js
  test/component/testDashboard.js
  test/component/testDocumentUpload.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1543
