Repository hmcts/probate-frontend, pull requests merged in 2022-05, with the labels that each got.

#1590 DTSPB-2760: Fix nightly full functional on PRs
  Jenkinsfile_CNP
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1590

#1646 Dtspb 247 Exec New
  app.js
  app/routes/updateinvite.js
  app/steps/ui/declaration/index.js
  app/steps/ui/executors/updateinvite/index.js
  app/utils/AdditionalExecutorInvite.js
  app/utils/UpdateExecutorInvite.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/unit/executors/testExecutorsUpdateInvite.js
  test/unit/utils/testUpdateExecutorInvite.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1646

#1648 DTSPB-2793: fix executor invite email sent flag
  app/steps/ui/executors/invite/index.js
  test/unit/executors/testExecutorsInvite.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1648

#1589 DTSPB-2688 remove instances of real email and phone number
  test/data/pacts/probate/submitMultipleExeDataClinet.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1589

#1652 DTSPB-2793: check executor.inviteId as well as executor.emailSent
  app/steps/ui/executors/additionalinvite/index.js
  app/steps/ui/executors/contactdetails/index.js
  app/wrappers/Executors.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/unit/executors/testExecutorsContactDetails.js
  test/unit/utils/testAdditionalExecutorInvite.js
  test/unit/wrappers/testExecutorsWrapper.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1652

#1588 DTSPB-2705 allow dob to equal dod for gop and intestacy
  app/steps/ui/deceased/details/index.js
  app/steps/ui/deceased/dob/index.js
  app/steps/ui/deceased/dod/index.js
  charts/probate-frontend/Chart.yaml
  test/component/deceased/testDetails.js
  test/component/deceased/testDoB.js
  test/component/deceased/testDoD.js
  test/unit/deceased/testDeceasedDetails.js
  test/unit/deceased/testDeceasedDob.js
  test/unit/deceased/testDeceasedDod.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1588, nightly

#1657 Dtspb 2804 opening times update
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/static/contact/template.html
  app/views/includes/help_details.html
  test/component/common/testCommonContent.js
  test/component/deceased/testDivorcePlace.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/pin/testPinSignIn.js
  test/component/static/testContactUs.js
  test/component/testDashboard.js
  test/component/testDocumentUpload.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1657
