Repository hmcts/probate-frontend, pull requests merged in 2022-09, with the labels that each got.

#1699 DTSPB-2913: Add preview and local envs to testing support route
  app/routes.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1699

#1701 DTSPB-2913: unit test
  test/unit/testRoutes.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1701

#1702 DTSPB-2913: update unit test
  test/unit/testRoutes.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1702

#1703 DTSPB-2913: fix sonar coverage setup
  sonar-project.properties
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1703

#1706 DTSSE-1790 Update README
  README.md
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1706

#1704 DTSPB-2913 e2e test fix for multiexecutors.js
  test/end-to-end/pages/declaration/declaration.js
  test/end-to-end/pages/equalityanddiversity/completedpage.js
  test/end-to-end/pages/equalityanddiversity/startpage.js
  test/end-to-end/pages/executors/address.js
  test/end-to-end/pages/executors/alias.js
  test/end-to-end/pages/executors/contactdetails.js
  test/end-to-end/pages/executors/notified.js
  test/end-to-end/pages/executors/roles.js
  test/end-to-end/pages/executors/whendied.js
  test/end-to-end/pages/executors/whodied.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1704
