Repository hmcts/probate-frontend, pull requests merged in 2022-03, with the labels that each got.

#1534 Dtspb 2170 duplicate telephone numbers
  app/resources/cy/translation/executors/contactdetails.json
  app/resources/en/translation/executors/contactdetails.json
  app/steps/ui/executors/contactdetails/index.js
  app/wrappers/Executors.js
  test/unit/executors/testExecutorsContactDetails.js
  test/unit/wrappers/testExecutorsWrapper.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1534

#1519 DTSPB-2479 fix ga tracking on summary page
  app/steps/ui/summary/index.js
  test/unit/testSummary.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1519

#1570 DTSPB-2675: minimist dependency warning
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1570

#1568 DTSPB-2670 do not clear declaration checkbox when signing in as co-exec
  app/steps/ui/pin/signin/index.js
  test/unit/pin/testSignIn.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1568

#1559 DTSPB-1493 add PA16 list item to send docs page and coversheet plus r…
  app/resources/cy/translation/documents.json
  app/resources/en/translation/documents.json
  app/services/CoverSheetPdf.js
  app/steps/ui/documents/index.js
  app/steps/ui/documents/template.html
  app/utils/DocumentPageUtil.js
  app/wrappers/Applicant.js
  app/wrappers/Deceased.js
  config/default.yaml
  test/component/testDocumentsPage.js
  test/unit/services/testCoverSheetPdf.js
  test/unit/testDocumentsPage.js
  test/unit/utils/testDocumentPageUtil.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1559

#1567 DTSPB-2555: fixed hint wording
  app/resources/cy/translation/screeners/willleft.json
  app/resources/cy/translation/screeners/willoriginal.json
  app/resources/en/translation/screeners/willleft.json
  app/resources/en/translation/screeners/willoriginal.json
  app/steps/ui/screeners/willleft/template.html
  app/steps/ui/screeners/willoriginal/template.html
  config/default.yaml
  test/component/screeners/testWillOriginal.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1567
