Repository hmcts/probate-frontend, pull requests merged in 2022-01, with the labels that each got.

#1517 DTSPB-2433 add send docs iht 207 text
  app/resources/cy/translation/documents.json
  app/resources/en/translation/documents.json
  app/steps/ui/documents/index.js
  app/steps/ui/documents/template.html
  test/component/testDocumentsPage.js
  test/unit/testDocumentsPage.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1517

#1521 DTSPB-2509 ee estate valued typo
  app/resources/en/translation/screeners/eeestatevalued.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1521

#1522 DTSPB-2510 probate estate values typos
  app/resources/en/translation/iht/probateestatevalues.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1522

#1527 DTSPB-2547: Add temporary-hint-text
  app/resources/en/translation/iht/ihtestatevalues.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1527

#1529 DTSPB_2549: Fix validation error message
  app/components/error.js
  app/resources/cy/translation/declaration.json
  app/resources/en/translation/declaration.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1529

#1530 Fix dependency issue
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1530

#1523 DTSPB-2138: fe changes
  app/core/runners/UIStepRunner.js
  config/default.yaml
  test/unit/core/testUIStepRunner.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1523

#1528 DTSPB-2456: force integer values for 3 EE fields
  app/resources/cy/translation/iht/ihtestatevalues.json
  app/resources/en/translation/iht/ihtestatevalues.json
  app/steps/ui/iht/ihtestatevalues/index.js
  app/utils/IhtEstateValuesUtil.js
  test/unit/iht/testIhtEstateValues.js
  test/unit/utils/testIhtEstateValuesUtil.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1528

#1536 DTSPB-2546: fix dep issues
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1536

#1533 DTSPB-2445 amend value of app to 273 on all hardcoded values
  app/resources/cy/translation/screeners/starteligibility.json
  app/resources/en/translation/screeners/starteligibility.json
  test/service-stubs/feesApi.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1533

#1538 DTSPB-2562 Change keywords for citizen journey
  config/default.yaml
  test/unit/services/testFees.js
  test/unit/services/testFeesLookup.js
  test/unit/utils/testFeesCalculator.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1538

#1539 Comment the full functional as taking very long to execute
  package.json
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1539

#1524 DTSPB-2530 fix external links
  .vscode/launch.json
  app/resources/cy/translation/iht/ihtestatevalues.json
  app/resources/cy/translation/iht/probateestatevalues.json
  app/resources/en/translation/iht/ihtestatevalues.json
  app/resources/en/translation/iht/probateestatevalues.json
  app/steps/ui/iht/ihtestatevalues/template.html
  app/steps/ui/iht/probateestatevalues/template.html
  config/default.yaml
  test/component/iht/testProbateEstateValues.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1524
