Repository hmcts/probate-frontend, pull requests merged in 2022-08, with the labels that each got.

#1681 Dtspb 1858 update pcq token algorithm
  app/middleware/completeEqualityTask.js
  app/steps/ui/equality/createToken.js
  charts/probate-frontend/values.preview.template.yaml
  test/service-stubs/equalityAndDiversityHealth.js
  test/unit/testEquality.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1681

#1689 Dtspb 2942 webchat 180 minutes ewt
  app/assets/javascripts/avaya-webchat-2.js
  app/assets/locales/avaya-webchat/locale_en-GB.json
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1689

#1695 DTSPB-2977 revert ewt changes
  app/assets/javascripts/avaya-webchat-2.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1695

#1697 Add backstage configuration file
  catalog-info.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1697

#1698 DTSPB-2977 force browsers to refresh avaya-webchat-2
  app/assets/javascripts/avaya-webchat-3.js
  app/views/includes/scripts.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1698
