Repository hmcts/probate-frontend, pull requests merged in 2022-04, with the labels that each got.

#1577 amend yarn.lock
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1577

#1580 Dtspb 2588 avaya survey
  app/assets/locales/avaya-webchat/locale_en-GB.json
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1580

#1571 Dtspb 2551 send docs list of documents
  app/utils/DocumentPageUtil.js
  test/unit/services/testCoverSheetPdf.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1571

#1585 DTSPB-2730 fix dep issue
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1585

#1586 DTSPB-2729 fix Send Documents Item at Written Wishes
  app/utils/DocumentPageUtil.js
  test/unit/services/testCoverSheetPdf.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1586
