Repository hmcts/probate-frontend, pull requests merged in 2023-03, with the labels that each got.

#1803 Dtspb 3282 Executor questions update
  app/resources/cy/translation/executors/alias.json
  app/resources/cy/translation/executors/names.json
  app/resources/cy/translation/executors/number.json
  app/resources/en/translation/executors/alias.json
  app/resources/en/translation/executors/names.json
  app/resources/en/translation/executors/number.json
  app/steps/ui/executors/names/index.js
  app/steps/ui/executors/names/schema.json
  app/steps/ui/executors/number/index.js
  app/steps/ui/executors/number/template.html
  test/data/pacts/probate/checkAnswersSummary.json
  test/end-to-end/pages/executors/number.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1803

#1807 DTSPB-3409 - Suppression fix
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1807

#1784 Update .terraform-version
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:probate, prd:probate, add-or-update, rel:probate-frontend-pr-1784

#1808 DTSPB-3418 - Look for terraform updates in renovate
  .github/renovate.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1808

#1809 fix for execNames field e2e from regex update
  test/end-to-end/pages/executors/names.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1809

#1810 DTSPB-3433 - Check whether we need useAuth and useHttps
  app.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-1810

#1800 CasePrinted from CaseCreated
  app/steps/ui/payment/status/index.js
  test/accessibility/a11yTest.js
  test/component/assets/testAssetsOverseas.js
  test/component/copies/testCopiesOverseas.js
  test/component/copies/testCopiesUk.js
  test/component/payment/testPaymentStatus.js
  test/component/testDashboard.js
  test/component/testDocumentsPage.js
  test/component/testRedirectToDocuments.js
  test/component/testThankYouPage.js
  test/data/complete-form-undeclared.json
  test/data/complete-form-will-condition-toggle-on.json
  test/data/complete-form.json
  test/data/pacts/probate/submitMultipleExeDataClinet.json
  test/data/pacts/probate/submitSingleExeDataClinet.json
  test/service-stubs/multipleApplications.js
  test/unit/middleware/testMultipleApplications.js
  test/unit/payment/testPaymentBreakdown.js
  test/unit/payment/testPaymentStatus.js
  test/unit/testDocumentsPage.js
  test/unit/testTasklist.js
  test/unit/testThankYouPage.js
  test/unit/utils/testFormatCcdCaseId.js
  test/unit/wrappers/testCcdCaseWrapper.js
Labels: ns:probate, prd:probate, nightly, nightly-without-welsh-tests, rel:probate-frontend-pr-1800

#1796 Dtspb 3324 Welsh screener pages
  app/resources/cy/translation/iht/estatevalued.json
  app/resources/cy/translation/screeners/applicantexecutor.json
  app/resources/cy/translation/screeners/deathcertificate.json
  app/resources/cy/translation/screeners/deathcertificateinenglish.json
  app/resources/cy/translation/screeners/deathcertificatetranslation.json
  app/resources/cy/translation/screeners/deceaseddomicile.json
  app/resources/cy/translation/screeners/diedafteroctober2014.json
  app/resources/cy/translation/screeners/eedeceaseddod.json
  app/resources/cy/translation/screeners/eeestatevalued.json
  app/resources/cy/translation/screeners/ihtcompleted.json
  app/resources/cy/translation/screeners/mentalcapacity.json
  app/resources/cy/translation/screeners/otherapplicants.json
  app/resources/cy/translation/screeners/relatedtodeceased.json
  app/resources/cy/translation/screeners/willleft.json
  app/resources/cy/translation/screeners/willoriginal.json
  app/resources/cy/translation/stoppage.json
  app/resources/en/translation/screeners/applicantexecutor.json
  app/resources/en/translation/screeners/deathcertificate.json
  app/resources/en/translation/screeners/deathcertificateinenglish.json
  app/resources/en/translation/screeners/deathcertificatetranslation.json
  app/resources/en/translation/screeners/deceaseddomicile.json
  app/resources/en/translation/screeners/diedafteroctober2014.json
  app/resources/en/translation/screeners/eedeceaseddod.json
  app/resources/en/translation/screeners/eeestatevalued.json
  app/resources/en/translation/screeners/ihtcompleted.json
  app/resources/en/translation/screeners/mentalcapacity.json
  app/resources/en/translation/screeners/otherapplicants.json
  app/resources/en/translation/screeners/relatedtodeceased.json
  app/resources/en/translation/screeners/willleft.json
  app/resources/en/translation/screeners/willoriginal.json
  app/resources/en/translation/stoppage.json
  app/steps/ui/screeners/applicantexecutor/template.html
  app/steps/ui/screeners/deceaseddomicile/template.html
  app/steps/ui/screeners/relatedtodeceased/template.html
  app/steps/ui/screeners/willleft/template.html
  app/steps/ui/screeners/willoriginal/template.html
  app/steps/ui/stoppage/index.js
  config/default.yaml
  test/component/screeners/testWillLeft.js
  test/component/screeners/testWillOriginal.js
  test/component/testStopPage.js
  test/data/pacts/probate/checkAnswersSummary.json
  test/data/pacts/probate/invalidNoTitleCheckAnswersSummary.json
  test/end-to-end/pages/screeners/applicantexecutor.js
  test/end-to-end/pages/screeners/deathcertificate.js
  test/end-to-end/pages/screeners/deathcertificateinenglish.js
  test/end-to-end/pages/screeners/deathcertificatetranslation.js
  test/end-to-end/pages/screeners/deceaseddomicile.js
  test/end-to-end/pages/screeners/eedeceaseddod.js
  test/end-to-end/pages/screeners/eevalue.js
  test/end-to-end/pages/screeners/ihtcompleted.js
  test/end-to-end/pages/screeners/mentalcapacity.js
  test/end-to-end/pages/screeners/otherapplicants.js
  test/end-to-end/pages/screeners/relatedtodeceased.js
  test/end-to-end/pages/screeners/willleft.js
  test/end-to-end/pages/screeners/willoriginal.js
  test/unit/testSoftStops.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1796

#1815 DTSPB-3451 - Remove reference to nsp
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1815

#1806 DTSPB-3005 - FE point to local orchestrator
  README.md
  package.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1806

#1792 DTSPB-3384 - Code refactor based on sonarscan recommendations
  app/core/steps/EligibilityValidationStep.js
  app/services/IdamSession.js
  app/services/Oauth2Token.js
  app/services/Security.js
  app/steps/ui/iht/ihtestatevalues/index.js
  app/steps/ui/will/codicilsdamagedate/index.js
  app/steps/ui/will/codicilshasvisibledamage/index.js
  app/steps/ui/will/willdamagedate/index.js
  app/utils/SessionStatusEnum.js
  config/default.yaml
  test/component/coapplicant/testCoApplicantDeclaration.js
  test/component/pin/testPinResend.js
  test/component/pin/testPinSignIn.js
  test/unit/services/testOauth2Token.js
  test/unit/services/testService.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1792

#1816 DTSPB-3454 - Upgrade rewire and mochawesome
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-1816

#1813 DTSPB-3433 - Remove useAuth and useHttps
  app.js
  app/components/utils.js
  config/custom-environment-variables.yaml
  config/default.yaml
  test/unit/components/testUtils.js
  test/util/commonConsts.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1813

#1805 DTSPB-3395 - Increase unit test coverage
  app/utils/ServiceAuthoriser.js
  test/unit/middleware/testSetServiceAuthorisationToken.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-1805

#1819 yarn upgrade
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1819

#1829 DTSPB-3498 Fix CVE
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1829

#1814 DTSPB-3402 Removed unnecesssary api-utils
  app/components/api-utils.js
  app/middleware/completeEqualityTask.js
  app/services/AllExecutorsAgreed.js
  app/services/Authorise.js
  app/services/Document.js
  app/services/FeesData.js
  app/services/FeesRegister.js
  app/services/FormData.js
  app/services/IdamSession.js
  app/services/InviteData.js
  app/services/InviteLink.js
  app/services/Oauth2Token.js
  app/services/Payment.js
  app/services/Pdf.js
  app/services/PinNumber.js
  app/services/Security.js
  app/services/Service.js
  app/services/SubmitData.js
  app/services/ValidateData.js
  app/utils/AsyncFetch.js
  test/unit/middleware/testCompleteEqualityTask.js
  test/unit/middleware/testMultipleApplications.js
  test/unit/services/testAllExecutorsAgreed.js
  test/unit/services/testAuthorise.js
  test/unit/services/testDocument.js
  test/unit/services/testFees.js
  test/unit/services/testFeesLookup.js
  test/unit/services/testIdamSession.js
  test/unit/services/testInviteData.js
  test/unit/services/testInviteLink.js
  test/unit/services/testOauth2Token.js
  test/unit/services/testPayment.js
  test/unit/services/testPinNumber.js
  test/unit/services/testService.js
  test/unit/services/testSubmitData.js
  test/unit/services/testValidateData.js
  test/unit/utils/testFeesCalculator.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-1814
