Repository hmcts/probate-frontend, pull requests merged in 2023-09, with the labels that each got.

#1890 DTSPB-3781
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1890

#1886 DTSPB-3709 Transformed Excepted estate journey
  app/resources/en/translation/iht/deceasedlatespousecivilpartner.json
  app/resources/en/translation/iht/ihtestatevalues.json
  app/resources/en/translation/iht/unusedallowanceclaimed.json
  app/steps/ui/iht/ihtestatevalues/schema.json
  app/steps/ui/iht/submittedtohmrc/index.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1886

#1883 DTSPB-3691 Added walesh translation on survey link
  app/resources/cy/translation/common.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1883

#1894 DTSPB-3807 move away from using Docker.io for our images and use our …
  charts/probate-frontend/values.preview.template.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1894
