Repository hmcts/probate-frontend, pull requests merged in 2023-11, with the labels that each got.

#1918 DTSPB- 3862 supress frontend
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1918

#1921 DTSPB-3867 Suppress Probate Frontend CVE
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1921

#1928 New nodejs Chart 3.0.1
  charts/probate-frontend/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1928

#1930 DTSPB-3758 Force update CSS
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/head.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1930
