Repository hmcts/probate-frontend, pull requests merged in 2023-10, with the labels that each got.

#1888 DTSPB-3705-New-HMRC-Code added two new pages and working on the valid…
  .github/renovate.json
  app/journeys/intestacy.js
  app/journeys/probate.js
  app/resources/cy/translation/common.json
  app/resources/cy/translation/iht/hmrcletter.json
  app/resources/cy/translation/iht/submittedtohmrc.json
  app/resources/cy/translation/iht/uniqueprobatecode.json
  app/resources/cy/translation/iht/waitingforhmrc.json
  app/resources/en/translation/iht/hmrcletter.json
  app/resources/en/translation/iht/submittedtohmrc.json
  app/resources/en/translation/iht/uniqueprobatecode.json
  app/resources/en/translation/iht/waitingforhmrc.json
  app/steps/ui/deceased/deathcertificate/index.js
  app/steps/ui/iht/hmrcletter/index.js
  app/steps/ui/iht/hmrcletter/schema.json
  app/steps/ui/iht/hmrcletter/template.html
  app/steps/ui/iht/submittedtohmrc/index.js
  app/steps/ui/iht/submittedtohmrc/template.html
  app/steps/ui/iht/uniqueprobatecode/index.js
  app/steps/ui/iht/uniqueprobatecode/schema.json
  app/steps/ui/iht/uniqueprobatecode/template.html
  app/steps/ui/iht/waitingforhmrc/index.js
  app/steps/ui/iht/waitingforhmrc/schema.json
  app/steps/ui/iht/waitingforhmrc/template.html
  app/utils/ExceptedEstateDod.js
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  test/component/deceased/testDeathCertificate.js
  test/unit/iht/testSubmittedToHmrc.js
  test/unit/iht/testhmrcletter.js
  test/unit/iht/testuniqueprobatecode.js
  test/unit/iht/testwaitingforhmrc.js
  yarn.lock
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1888

#1904 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:probate, prd:probate, destroy, rel:probate-frontend-pr-1904

#1908 DTSPB 3839 remove renovate automerge
  .github/renovate.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1908
