Repository hmcts/probate-frontend, pull requests merged in 2023-01, with the labels that each got.

#1745 DTSPB-2699 CVE suppression
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1745

#1748 Dtspb 3261
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1748

#1732 Dtspb 3087 will content changes
  app/resources/cy/translation/will/codicils.json
  app/resources/cy/translation/will/codicilsdamageculpritknown.json
  app/resources/cy/translation/will/codicilsdamagedate.json
  app/resources/cy/translation/will/codicilsdamagereasonknown.json
  app/resources/cy/translation/will/codicilshasvisibledamage.json
  app/resources/cy/translation/will/codicilsnumber.json
  app/resources/cy/translation/will/willdamageculpritknown.json
  app/resources/cy/translation/will/willdamagedate.json
  app/resources/cy/translation/will/willdamagereasonknown.json
  app/resources/cy/translation/will/willhasvisibledamage.json
  app/resources/en/translation/will/codicils.json
  app/resources/en/translation/will/codicilsdamageculpritknown.json
  app/resources/en/translation/will/codicilsdamagedate.json
  app/resources/en/translation/will/codicilsdamagereasonknown.json
  app/resources/en/translation/will/codicilshasvisibledamage.json
  app/resources/en/translation/will/codicilsnumber.json
  app/resources/en/translation/will/willdamageculpritknown.json
  app/resources/en/translation/will/willdamagedate.json
  app/resources/en/translation/will/willdamagereasonknown.json
  app/resources/en/translation/will/willhasvisibledamage.json
  app/steps/ui/will/codicils/template.html
  app/steps/ui/will/codicilsdamageculpritknown/template.html
  app/steps/ui/will/codicilsdamagedate/template.html
  app/steps/ui/will/codicilsdamagereasonknown/template.html
  app/steps/ui/will/codicilshasvisibledamage/template.html
  app/steps/ui/will/codicilsnumber/index.js
  app/steps/ui/will/codicilsnumber/schema.json
  app/steps/ui/will/willdamageculpritknown/template.html
  app/steps/ui/will/willdamagedate/template.html
  app/steps/ui/will/willdamagereasonknown/template.html
  app/steps/ui/will/willhasvisibledamage/template.html
  test/component/will/testWillCodicilsNumber.js
  test/unit/will/testCodicilsDamageDate.js
  test/unit/will/testWillDamageDate.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1732

#1750 Dtspb 3281 correct cves
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1750

#1757 DTSPB-3295: cannot upgrade healthcheck - suppressed further
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1757

#1760 New chart released for DNS update in Demo
  charts/probate-frontend/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1760

#1766 DTSPB-3304 - Add new tag for pr nightly
  Jenkinsfile_CNP
  package.json
  test/end-to-end/paths/generic/survey.test.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/other/creditCardPaymentCancellation.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1766

#1771 DTSPB-3308 - One PR per dependency in renovate
  .github/renovate.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1771
