Repository hmcts/probate-frontend, pull requests merged in 2023-07, with the labels that each got.

#1870 Dtspb 3659 suppress CVE
  app/steps/ui/payment/breakdown/index.js
  test/unit/testTasklist.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1870

#1871 Dtspb 3588 e2e fix check survey
  test/end-to-end/pages/thankyou/thankyou.js
  test/end-to-end/paths/generic/survey.test.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1871

#1872 DTSPB-3684 Fix CVE suppression for Probate Frontend
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1872

#1876 DTSPB-3588 Update survey Link
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  app/steps/ui/citizenshub/template.html
  app/steps/ui/thankyou/template.html
  app/views/errors/error.html
  app/views/includes/layout.html
  config/default.yaml
  test/end-to-end/paths/generic/survey.test.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-1876
