Repository hmcts/probate-frontend, pull requests merged in 2023-02, with the labels that each got.

#1770 Dtspb 3260
  app/steps/ui/deceased/details/template.html
  app/steps/ui/deceased/dob/template.html
  app/steps/ui/deceased/dod/template.html
  app/steps/ui/will/codicilshasvisibledamage/template.html
  app/steps/ui/will/willhasvisibledamage/template.html
  test/end-to-end/pages/deceased/details.js
  test/end-to-end/pages/deceased/dob.js
  test/end-to-end/pages/deceased/dod.js
  test/end-to-end/pages/will/codicilsdamage.js
  test/end-to-end/pages/will/willdamage.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-1770

#1782 cve fixes
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1782

#1769 DTSPB-3241 - Add content to indicate IHT service is closed (v2)
  app/resources/cy/translation/iht/method.json
  app/resources/en/translation/iht/method.json
  app/steps/ui/iht/method/index.js
  app/steps/ui/iht/method/template.html
  package.json
  test/unit/iht/testIhtMethod.js
  test/unit/middleware/testDocumentUpload.js
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1769

#1783 DTSPB-3211 fix after to afterAlways or afterSuccess
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1783

#1765 DTSPB-3276 - Point FE to AAT (v2)
  README.md
  app/setupSecrets.js
  config/dev-aat.yaml
  package.json
  test/unit/services/testOauth2Token.js
  test/unit/testSetupSecrets.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1765

#1786 Update Chart.yaml
  charts/probate-frontend/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1786

#1761 DTSPB-3300 - Fix broken FE unit tests
  .gitignore
  config/testing-component.yaml
  config/testing-unit.yaml
  package.json
  test/unit/executors/testExecutorsUpdateInvite.js
  test/unit/middleware/testCompleteEqualityTask.js
  test/unit/middleware/testDocumentDownload.js
  test/unit/middleware/testDocumentUpload.js
  test/unit/middleware/testMultipleApplications.js
  test/unit/pin/testPinResend.js
  test/unit/pin/testSignIn.js
  test/unit/services/testAllExecutorsAgreed.js
  test/unit/services/testAuthorise.js
  test/unit/services/testDocument.js
  test/unit/services/testFees.js
  test/unit/services/testIdamSession.js
  test/unit/services/testInviteData.js
  test/unit/services/testInviteLink.js
  test/unit/services/testPayment.js
  test/unit/services/testPinNumber.js
  test/unit/services/testPostcodeAddress.js
  test/unit/services/testService.js
  test/unit/services/testSubmitData.js
  test/unit/services/testValidateData.js
  test/unit/testEquality.js
  test/unit/utils/testFeesCalculator.js
  test/unit/utils/testSetupHealthCheck.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1761

#1790 Suppress cacheable-request dep issue
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1790

#1785 DTSPB-3338 - Tidy config
  app/journeyCheck.js
  app/routes.js
  config/default.yaml
  config/test-dk.yaml
  config/test.yaml
  config/testing-dk.yaml
  config/testing-e2e-local-to-aat.yaml
  config/testing-e2e.yaml
  config/testing-http-dk.yaml
  config/testing-http.yaml
  config/testing-unit.yaml
  test/accessibility/a11yTest.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1785

#1743 DTSPB-3177: after replacesments
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1743

#1798 DTSPB-3372 - Add option to only run English tests for e2e nightly run
  Jenkinsfile_CNP
  README.md
  test/accessibility/a11yTest.js
  test/end-to-end/helpers/GeneralHelpers.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/other/creditCardPaymentCancellation.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1798, nightly-without-welsh-tests

#1795 DTSPB-3287 - Yarn v3
  .gitignore
  .nycrc.json
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  config/test.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1795, nightly-without-welsh-tests

#1802 Revert "DTSPB-3287 - Yarn v3 (#1795)"
  .gitignore
  .nycrc.json
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  config/test.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1802

#1801 DTSPB-3357 - Fix timeout page v2
  config/default.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1801

#1804 DTSPB-3287 - Yarn v3 (attempt 2)
  .gitignore
  .nycrc.json
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  config/test.yaml
  package.json
  sonar-project.properties
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-1804
