Repository hmcts/probate-frontend, pull requests merged in 2024-11, with the labels that each got.

#2267 DTSPB-4420: Fix Acorn CVE
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2267

#2198 DTSPB-4367 - Bilingual Legal Statement
  app/resources/cy/translation/declaration.json
  app/steps/ui/declaration/index.js
  app/utils/FormatAlias.js
  charts/probate-frontend/Chart.yaml
  test/component/testDeclarationPageMultipleApplicants.js
  test/component/testDeclarationPageSingleApplicant.js
  test/unit/testDeclaration.js
  test/unit/utils/testFormatAlias.js
  test/unit/utils/testIntestacyDeclarationFactory.js
  test/unit/utils/testProbateDeclarationFactory.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-2198

#2288 DTSPB-4240 | Updated E2E tests with Important: read before you start …
  test/end-to-end/pages/screeners/starteligibility.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2288

#2293 Notification banner on CitizenHub page
  app/resources/cy/translation/citizenshub.json
  app/resources/en/translation/citizenshub.json
  app/steps/ui/citizenshub/template.html
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-2293
