Repository hmcts/probate-frontend, pull requests merged in 2024-12, with the labels that each got.

#2311 Change prod script tag and removed sessionReplay method as not used
  app/assets/javascripts/cookie-banner.js
  app/views/includes/layout.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2311

#2270 DTSPB-4378 Resolve text consistency issues when codicils are present
  app/resources/cy/translation/applicant/nameasonwill.json
  app/resources/en/translation/applicant/nameasonwill.json
  app/steps/ui/applicant/nameasonwill/index.js
  app/steps/ui/summary/includes/executors-applicant.njk
  app/steps/ui/summary/index.js
  test/component/applicant/testNameAsOnWill.js
  test/unit/applicant/testApplicantNameAsOnWill.js
  test/unit/testSummary.js
  test/unit/testSummaryCodicils.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2270

#2258 DTSPB-4240 Start eligibility screen changes
  app/components/step-utils.js
  app/resources/cy/translation/screeners/starteligibility.json
  app/resources/en/translation/screeners/starteligibility.json
  app/steps/ui/screeners/starteligibility/index.js
  app/steps/ui/screeners/starteligibility/template.html
  test/component/screeners/testStartEligibilityPage.js
  test/end-to-end/pages/screeners/starteligibility.js
  test/unit/screeners/testStartEligibility.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2258

#2326 Dtspb 4447 fix rfi google tag manager submit element order
  app/steps/ui/provideinformation/template.html
Labels: ns:probate, prd:probate, nightly, enable_keep_helm, rel:probate-frontend-pr-2326

#2340 update nightly run time
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2340
