Repository hmcts/probate-frontend, pull requests merged in 2024-04, with the labels that each got.

#1987 DTSPB-4118 new chart version for enabling hpa
  charts/probate-frontend/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1987

#1990 DTSPB-4135 update tar package
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1990

#1998 DTSPB-4158: Formidable CVE
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1998
