Repository hmcts/probate-frontend, pull requests merged in 2024-05, with the labels that each got.

#1997 DTSPB-4085 Probate Fees Increase
  app/resources/cy/translation/screeners/starteligibility.json
  app/resources/en/translation/screeners/starteligibility.json
  test/service-stubs/feesApi.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1997

#2006 Dtspb 4078 e2e eligibility journey changes
  test/end-to-end/paths/generic/survey.test.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/other/creditCardPaymentCancellation.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-2006

#2010 DTSPB-4194 change nightly execution time
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2010
