Repository hmcts/probate-frontend, pull requests merged in 2024-03, with the labels that each got.

#1971 DTSPB-4061 fix IHT400 & HMRC Letter No 504 issue
  app/steps/ui/iht/hmrcletter/index.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1971

#1973 DTSPB-3908 change to AppInsight_connection_String
  app/setupSecrets.js
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  server.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1973

#1975 Nightly dev
  test/java/build.gradle
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1975

#1977 Fix FE Nightly failure for e2e tests on Payment button
  test/end-to-end/pages/payment/govukpayment.js
Labels: ns:probate, prd:probate, nightly, enable_keep_helm, rel:probate-frontend-pr-1977

#1897 Add welsh locale to webchat
  app/assets/locales/avaya-webchat/en-cy/locale_en-GB.json
  app/assets/locales/avaya-webchat/en-en/locale_en-GB.json
  app/resources/cy/translation/common.json
  app/resources/cy/translation/static/avaya-webchat-cy.json
  app/resources/en/translation/static/avaya-webchat-cy.json
  app/steps/ui/citizenshub/template.html
  app/steps/ui/static/avaya-webchat/template.html
  app/steps/ui/static/contact/template.html
  app/views/includes/avaya-webchat.html
  app/views/includes/help_details.html
  app/views/includes/scripts.html
  test/unit/static/testAvayaWebchat.js
Labels: ns:probate, prd:probate, nightly, add-or-update, enable_keep_helm, rel:probate-frontend-pr-1897

#1976 DTSPB-4037 CitizenHub Update Stop State Message
  app/resources/cy/translation/citizenshub.json
  app/resources/en/translation/citizenshub.json
Labels: ns:probate, prd:probate, nightly, enable_keep_helm, rel:probate-frontend-pr-1976

#1985 update suppressions
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1985

#1986 DTSPB-4114 updated the express package .
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1986
