Repository hmcts/probate-frontend, pull requests merged in 2024-02, with the labels that each got.

#1946 DTSPB-3970 Fixed allowed number in Unique code
  app/steps/ui/iht/uniqueprobatecode/schema.json
  app/steps/ui/iht/uniqueprobatecode/template.html
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1946

#1953 DTSPB-4029 Suppress Frontend CVE
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1953

#1952 DTSPB-4024 Changed telephone Timings
  app/resources/en/translation/common.json
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1952

#1965 DTSPB-4033 Adding Google Tag Manager to /copies-summary page on Probate Journey
  app/steps/ui/copies/summary/index.js
  sonar-project.properties
  test/unit/copies/testCopiesSummary.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1965

#1943 DTSPB-3463: Added logic to display Error component on 400 error
  app/core/runners/UIStepRunner.js
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  charts/probate-frontend/Chart.yaml
  test/component/copies/testCopiesUk.js
  test/component/deceased/testDivorcePlace.js
  test/component/deceased/testOtherNames.js
  test/component/executors/testExecutorCurrentName.js
  test/component/executors/testExecutorCurrentNameReason.js
  test/component/executors/testExecutorsAdditionalInvite.js
  test/component/executors/testExecutorsAdditionalInviteSent.js
  test/component/executors/testExecutorsContactDetails.js
  test/component/executors/testExecutorsDealing.js
  test/component/executors/testExecutorsNames.js
  test/component/executors/testExecutorsUpdateInvite.js
  test/component/executors/testExecutorsWhenDied.js
  test/component/executors/testExecutorsWhoDied.js
  test/component/executors/testNotified.js
  test/component/executors/testRoles.js
  test/component/testDeclarationIntestacy.js
  test/component/testDeclarationPageSingleApplicant.js
  test/unit/core/testUIStepRunner.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-1943

#1962 DTSPB-2849 FE Puppeteer To Playwright Helper 3
  .gitignore
  app/resources/cy/translation/payment/status.json
  app/resources/en/translation/payment/status.json
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/PlaywrightHelper.js
  test/end-to-end/saucelabs.conf.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, nightly, enable_keep_helm, rel:probate-frontend-pr-1962

#1969 DTSPB-2849 : Remove microsoft browser from shell command
  bin/run-crossbrowser-tests.sh
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1969

#1968 DTSPB-3967 add fortify scan
  Jenkinsfile_nightly
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-1968
