Repository hmcts/probate-frontend, pull requests merged in 2024-10, with the labels that each got.

#2101 DTSPB-4295 Applicant Name Enhancement
  app/resources/cy/translation/applicant/alias.json
  app/resources/cy/translation/applicant/aliasreason.json
  app/resources/cy/translation/applicant/name.json
  app/resources/cy/translation/applicant/nameasonwill.json
  app/resources/cy/translation/declaration.json
  app/resources/en/translation/applicant/alias.json
  app/resources/en/translation/applicant/aliasreason.json
  app/resources/en/translation/applicant/name.json
  app/resources/en/translation/applicant/nameasonwill.json
  app/resources/en/translation/declaration.json
  app/steps/ui/applicant/aliasreason/template.html
  app/steps/ui/applicant/name/template.html
  app/steps/ui/applicant/nameasonwill/template.html
  app/steps/ui/declaration/index.js
  app/steps/ui/summary/includes/executors-applicant.njk
  app/utils/FormatAlias.js
  charts/probate-frontend/Chart.yaml
  test/component/applicant/testAlias.js
  test/component/applicant/testAliasReason.js
  test/component/summary/testExecutorsSection.js
  test/component/testDeclarationPageMultipleApplicants.js
  test/unit/testDeclaration.js
  test/unit/utils/testFormatAlias.js
  yarn.lock
Labels: ns:probate, prd:probate, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:probate-frontend-pr-2101

#2188 DTSPB-4377 fix GTM submit element order
  app/steps/ui/applicant/address/template.html
  app/steps/ui/deceased/address/template.html
  app/steps/ui/executors/address/template.html
  app/views/includes/two_thirds_form.html
Labels: ns:probate, prd:probate, nightly, enable_keep_helm, rel:probate-frontend-pr-2188

#2141 DTSPB-3185: Build new address object so change can be detected
  app/wrappers/DetectDataChange.js
  test/unit/wrappers/testDetectDataChange.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2141
