Repository hmcts/probate-frontend, pull requests merged in 2025-09, with the labels that each got.

#2694 DTSPB-4909 update welsh opening hours text.
  app/resources/cy/translation/common.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2694

#2719 DTSPB-4937 move bitnami chart to hmcts acr
  charts/probate-frontend/Chart.yaml
  charts/probate-frontend/values.preview.template.yaml
  charts/probate-frontend/values.yaml
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2719

#2773 DTSPB-4918 correctly render back link in welsh
  app/views/includes/layout.html
Labels: ns:probate, prd:probate, nightly, enable_keep_helm, rel:probate-frontend-pr-2773

#2737 DTSPB-4942 correct no payment submission
  app/steps/ui/payment/breakdown/index.js
  app/steps/ui/payment/status/index.js
  test/end-to-end/pages/payment/paymentbreakdown.js
  test/end-to-end/paths/generic/survey.test.js
  test/unit/payment/testPaymentBreakdown.js
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-2737
