Repository hmcts/probate-frontend, pull requests merged in 2025-06, with the labels that each got.

#2505 DTSPB-4451 Accessibility Meaningful Progressbar
  app/resources/cy/translation/citizenshub.json
  app/resources/cy/translation/thankyou.json
  app/resources/en/translation/citizenshub.json
  app/resources/en/translation/thankyou.json
  app/steps/ui/citizenshub/template.html
  app/steps/ui/thankyou/template.html
  test/component/testThankYouPage.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2505

#2564 Fix cve
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2564

#2584 DTSPB-4854 update renovate
  .github/renovate.json
  test/java/build.gradle
  test/java/gradle/wrapper/gradle-wrapper.properties
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2584
