Repository hmcts/probate-frontend, pull requests merged in 2025-04, with the labels that each got.

#2425 DTSPB-4563 update deceased married page with new text
  app/resources/cy/translation/deceased/married.json
  app/resources/en/translation/deceased/married.json
  test/end-to-end/pages/deceased/married.js
  test/unit/testSummary.js
  test/unit/testSummaryCodicils.js
  yarn-audit-known-issues
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, rel:probate-frontend-pr-2425

#2424 DTSPB-4564 do not default bilingual
  app/steps/ui/language/index.js
  app/steps/ui/language/template.html
  test/end-to-end/pages/language/bilingualgrant.js
  test/unit/testLanguage.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2424

#2389 DTSPB-4541 Hide Save & Close
  app/steps/ui/declaration/template.html
  test/component/testDeclarationPageSingleApplicant.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2389

#2429 DTSPB-4672 sanitise phone number in Executor contact details page
  app/steps/ui/executors/contactdetails/index.js
  test/unit/executors/testExecutorsContactDetails.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-2429

#2426 DTSPB-4569 Simplify Eligibility DOD
  app/journeys/intestacy.js
  app/journeys/probate.js
  app/steps/ui/screeners/willleft/index.js
  config/default.yaml
  test/end-to-end/pages/screeners/eedeceaseddod.js
  test/end-to-end/paths/generic/survey.test.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.en.test.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.no.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
  test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
  test/end-to-end/paths/other/creditCardPaymentCancellation.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
  test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
  test/unit/screeners/testDiedAfterOctober2014.js
  test/unit/screeners/testRelatedToDeceased.js
  test/unit/screeners/testWillLeft.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2426

#2430 DTSPB-4459: Initial template change, removing notification banner
  app/steps/ui/citizenshub/template.html
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2430

#2427 DTSPB-4449 Add new tab text to IHT links
  app/resources/cy/translation/screeners/eeestatevalued.json
  app/resources/cy/translation/screeners/starteligibility.json
  app/resources/cy/translation/screeners/willleft.json
  app/resources/cy/translation/stoppage.json
  app/resources/en/translation/screeners/eeestatevalued.json
  app/resources/en/translation/screeners/starteligibility.json
  app/resources/en/translation/screeners/willleft.json
  app/resources/en/translation/stoppage.json
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2427

#2465 DTSPB-4721: Resolve tar-fs due to vuln
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2465

#2435 add assertive aria tag to error summary
  app/views/includes/error_summary.html
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2435

#2451 DTSPB-4713 Resolve issues with templates preventing case submission
  app/core/runners/UIStepRunner.js
  app/steps/ui/summary/includes/executors-others-not-applying.njk
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2451

#2444 DTSPB-4700 rename executorsAllAlive to anyexecutorsdied
  app/journeyCheck.js
  app/journeys/probate.js
  app/resources/cy/translation/executors/anyexecutorsdied.json
  app/resources/en/translation/executors/anyexecutorsdied.json
  app/steps/ui/executors/anyexecutorsdied/index.js
  app/steps/ui/executors/anyexecutorsdied/schema.json
  app/steps/ui/executors/anyexecutorsdied/template.html
  app/steps/ui/summary/includes/executors.njk
  test/component/executors/testAnyExecutorsDied.js
  test/component/summary/testExecutorsSection.js
  test/data/complete-form-multipleapplicants.json
  test/data/complete-form-will-condition-toggle-on.json
  test/data/complete-form.json
  test/data/copiesUk.json
  test/data/pacts/probate/submitMultipleExeDataClinet.json
  test/data/pacts/probateDraftFormWithExecutors.json
  test/data/pacts/probateDraftFormWithExecutorsResponse.json
  test/data/summary-executors.json
  test/end-to-end/pages/executors/anyExecutorsDied.js
  test/end-to-end/pages/steps.js
  test/end-to-end/paths/probate/multipleExecutors.EE.no.js
  test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
  test/end-to-end/paths/probate/multipleExecutors.js
  test/unit/executors/testAnyExecutorsDied.js
  test/unit/utils/testRemoveInvitedExecutor.js
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2444
