Repository hmcts/probate-frontend, pull requests merged in 2025-07, with the labels that each got.

#2612 bump nodejs-healthcheck to 1.8.6
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2612

#2593 DTSPB-4792 Prevent prototype pollution
  app.js
  app/components/error.js
  app/core/runners/UIStepRunner.js
  app/core/steps/Step.js
  app/core/steps/ValidationStep.js
  app/steps/ui/coapplicant/declaration/index.js
  app/steps/ui/declaration/index.js
  app/steps/ui/executors/alias/index.js
  app/steps/ui/executors/currentnamereason/index.js
  app/steps/ui/executors/invite/index.js
  app/steps/ui/executors/updateinvite/index.js
  app/utils/AdditionalExecutorInvite.js
  app/utils/Sanitize.js
  test/unit/testLanguage.js
  test/unit/utils/testSanitize.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, rel:probate-frontend-pr-2593

#2604 DTSPB-4611 Migrate to sass
  app/assets/sass/application-ie8.scss
  app/assets/sass/application.scss
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/head.html
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-2604

#2636 Revert "DTSPB-4792 Prevent prototype pollution"
  app.js
  app/components/error.js
  app/core/runners/UIStepRunner.js
  app/core/steps/Step.js
  app/core/steps/ValidationStep.js
  app/steps/ui/coapplicant/declaration/index.js
  app/steps/ui/declaration/index.js
  app/steps/ui/executors/alias/index.js
  app/steps/ui/executors/currentnamereason/index.js
  app/steps/ui/executors/invite/index.js
  app/steps/ui/executors/updateinvite/index.js
  app/utils/AdditionalExecutorInvite.js
  app/utils/Sanitize.js
  test/unit/testLanguage.js
  test/unit/utils/testSanitize.js
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-2636

#2652 DTSPB-4490 Updated privacy policy from 90 to 180 days
  app/resources/cy/translation/static/privacy.json
  app/resources/en/translation/static/privacy.json
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2652
