Repository hmcts/probate-frontend, pull requests merged in 2025-01, with the labels that each got.

#2363 update timeliness references on frontend pages and citizen hub
  app/resources/cy/translation/citizenshub.json
  app/resources/cy/translation/coapplicant/agreepage.json
  app/resources/cy/translation/payment/status.json
  app/resources/cy/translation/thankyou.json
  app/resources/en/translation/citizenshub.json
  app/resources/en/translation/coapplicant/agreepage.json
  app/resources/en/translation/payment/status.json
  app/resources/en/translation/thankyou.json
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, rel:probate-frontend-pr-2363

#2319 DTSPB-4136 add Deceased Name to question & error Message
  app/resources/cy/translation/documents.json
  app/resources/cy/translation/thankyou.json
  app/resources/cy/translation/will/deceasedwrittenwishes.json
  app/resources/en/translation/documents.json
  app/resources/en/translation/thankyou.json
  app/resources/en/translation/will/deceasedwrittenwishes.json
  app/steps/ui/summary/includes/codicilsconditions.njk
  app/steps/ui/summary/index.js
  app/steps/ui/will/deceasedwrittenwishes/index.js
  app/steps/ui/will/deceasedwrittenwishes/template.html
  test/component/summary/testCodicilsSection.js
  test/component/will/testDeceasedWrittenWishes.js
  test/data/will/codicils.json
  test/unit/services/coversheet/testCoverSheetPdf.js
  test/unit/testSummary.js
Labels: ns:probate, prd:probate, aat/add-or-update, prod/add-or-update, rel:probate-frontend-pr-2319

#2386 DTSPB-4537 suppress CVE for lodash.isequal: 4.5.0
  yarn-audit-known-issues
Labels: ns:probate, prd:probate

#2379 DTSPB-4533 Fixed the Address issue
  app/wrappers/DetectDataChange.js
  test/unit/wrappers/testDetectDataChange.js
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes
