Repository hmcts/probate-frontend, pull requests merged in 2025-03, with the labels that each got.

#2395 DTSPB-4475 Retain and Disposal
  app/core/runners/UIStepRunner.js
  app/resources/cy/translation/tasklist.json
  app/resources/en/translation/tasklist.json
  app/serviceAuthorisation.js
  app/services/Security.js
  app/steps/ui/tasklist/index.js
  app/steps/ui/tasklist/template.html
  app/utils/DateValidation.js
  app/views/includes/scripts.html
  config/custom-environment-variables.yaml
  config/default.yaml
  test/data/complete-form-will-condition-toggle-on.json
  test/unit/services/testSecurity.js
  test/unit/testTasklist.js
  test/unit/utils/testDateValidation.js
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, rel:probate-frontend-pr-2395

#2306 DTSPB-4390 address security scan issues
  app.js
  app/middleware/setSessionLanguage.js
  config/default.yaml
  package.json
  test/component/testHelmet.js
  test/unit/middleware/testSetSessionLanguage.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2306

#2415 DTSPB-4586 update helm urls to use oci
  charts/probate-frontend/Chart.yaml
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2415

#2417 DTSPB-4649 Fix CVE
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, nightly-without-welsh-tests, enable_keep_helm, rel:probate-frontend-pr-2417

#2364 DTSPB- 4457 added H2 tag to cookies banner
  app/views/includes/cookie-banner.html
  test/accessibility/a11yTest.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2364

#2387 DTSPB-4462 Modify zoom behaviour
  app/assets/sass/patterns/_dashboard.scss
  app/steps/ui/dashboard/template.html
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/head.html
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2387

#2380 DTSPB-4458 Add a11y context for summary page links
  app/steps/ui/dashboard/template.html
  app/views/widgets/checkanswer.njk
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2380

#2411 DTSPB-4565 remove back link from co-applicant pages
  app/components/step-utils.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2411

#2416 DTSPB-4626 Make status comparison case insensitive for payments.
  app/services/Payment.js
  app/steps/ui/payment/breakdown/index.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2416

#2423 DTSPB-4660 fix heading bold for GOV.UK
  app/steps/ui/dashboard/template.html
  app/steps/ui/static/avaya-webchat/template.html
  app/views/includes/head.html
  app/views/includes/layout.html
Labels: ns:probate, prd:probate, enable_keep_helm, rel:probate-frontend-pr-2423

#2428 DTSPB-4361 removed logs
  app/steps/ui/executors/named/index.js
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2428
