Repository hmcts/probate-frontend, pull requests merged in 2025-02, with the labels that each got.

#2397 Revert "Update dependency file-type"
  package.json
  yarn.lock
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2397

#2404 remove request as dependency to replace with Axios
  package.json
  test/end-to-end/helpers/TestConfigurator.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-2404

#2371 DTSPB-4427 Deceased alias on will does not appear on citizen application legal statement
  app/steps/ui/declaration/index.js
  test/unit/testDeclaration.js
Labels: ns:probate, prd:probate, aat/add-or-update, prod/no-changes, rel:probate-frontend-pr-2371

#2410 enable corepack, update yarn calls to work in v4.
  Dockerfile
Labels: ns:probate, prd:probate, rel:probate-frontend-pr-2410

#2348 DTSPB-4477: Increase max mobile number length
  app/steps/ui/executors/contactdetails/index.js
  app/steps/ui/executors/contactdetails/schema.json
  app/utils/PhoneNumberValidator.js
  package.json
  test/unit/utils/testPhoneNumberValidator.js
  yarn.lock
Labels: ns:probate, prd:probate, nightly, rel:probate-frontend-pr-2348
